# Chapter 4: Column Deep Dive

**Purpose:** Analyze each column in detail with distribution analysis, value validation, and transformation recommendations.

**What you'll learn:**
- How to validate value ranges for different column types
- How to interpret distribution shapes (skewness, kurtosis)
- When and why to apply transformations (log, sqrt, capping)
- How to detect zero-inflation and handle it

**Outputs:**
- Value range validation results
- Per-column distribution visualizations with statistics
- Skewness/kurtosis analysis with transformation recommendations
- Zero-inflation detection
- Type confirmation/override capability
- Updated exploration findings

## 4.1 Load Previous Findings

In [1]:
from customer_retention.analysis.notebook_progress import track_and_export_previous

track_and_export_previous("04_column_deep_dive.ipynb")

import numpy as np
import plotly.graph_objects as go
from scipy import stats

from customer_retention.analysis.auto_explorer import ExplorationFindings, RecommendationRegistry
from customer_retention.analysis.visualization import ChartBuilder, console, display_figure, display_table
from customer_retention.core.compat import native_pd, to_datetime
from customer_retention.core.config.column_config import ColumnType
from customer_retention.core.config.experiments import (
    FINDINGS_DIR,
)
from customer_retention.stages.profiling import (
    CategoricalDistributionAnalyzer,
    DistributionAnalyzer,
    TemporalAnalyzer,
    TemporalGranularity,
    TransformationType,
)
from customer_retention.stages.validation import DataValidator, RuleGenerator

WARNING:pyspark.pandas.usage_logger:Tried to attach usage logger `pyspark.databricks.pandas.usage_logger`, but an exception was raised: JVM wasn't initialised. Did you call it on executor side?

In [2]:
from customer_retention.analysis.auto_explorer import load_notebook_findings

FINDINGS_PATH, _namespace, dataset_name = load_notebook_findings("04_column_deep_dive.ipynb")
print(f"Using: {FINDINGS_PATH}")

findings = ExplorationFindings.load(FINDINGS_PATH)
print(f"\nLoaded findings for {findings.column_count} columns from {findings.source_path}")

# Warn if this is event-level data (should run 01d first)
if findings.is_time_series and "_aggregated" not in FINDINGS_PATH:
    ts_meta = findings.time_series_metadata
    print("\n\u26a0\ufe0f  WARNING: This appears to be EVENT-LEVEL data")
    print(f"   Entity: {ts_meta.entity_column}, Time: {ts_meta.time_column}")
    print("   Recommendation: Run 01d_event_aggregation.ipynb first to create entity-level data")

Using: /Users/Vital/python/CustomerRetention/experiments/runs/email-f00adbd9/datasets/customer_emails/findings/customer_emails_aggregated_findings.yaml

Loaded findings for 252 columns from /Users/Vital/python/CustomerRetention/experiments/runs/email-f00adbd9/data/bronze/customer_emails_aggregated

## 4.2 Load Source Data

In [3]:
# Load data - handle aggregated data (parquet or Delta Lake)
from pathlib import Path

from customer_retention.analysis.auto_explorer.active_dataset_store import load_active_dataset
from customer_retention.stages.temporal import TEMPORAL_METADATA_COLS

# For aggregated data, load directly from the source path
if "_aggregated" in FINDINGS_PATH:
    source_path = Path(findings.source_path)
    if not source_path.is_absolute():
        source_path = Path("..") / source_path
    if source_path.is_dir():
        from customer_retention.integrations.adapters.factory import get_delta
        df = get_delta(force_local=True).read(str(source_path))
    elif source_path.is_file():
        df = native_pd.read_parquet(source_path)
    else:
        df = load_active_dataset(_namespace, dataset_name)
    data_source = f"aggregated:{source_path.name}"
else:
    # Standard loading for event-level or entity-level data
    df = load_active_dataset(_namespace, dataset_name)
    data_source = dataset_name

print(f"Loaded data from: {data_source}")
print(f"Shape: {df.shape}")

charts = ChartBuilder()

# Initialize recommendation registry for this exploration
registry = RecommendationRegistry()
registry.init_bronze(findings.source_path)

# Find target column for Gold layer initialization
target_col = next((name for name, col in findings.columns.items() if col.inferred_type == ColumnType.TARGET), None)
if target_col:
    registry.init_gold(target_col)

# Find entity column for Silver layer initialization
entity_col = next((name for name, col in findings.columns.items() if col.inferred_type == ColumnType.IDENTIFIER), None)
if entity_col:
    registry.init_silver(entity_col)

print(f"Initialized recommendation registry (Bronze: {findings.source_path})")

Loaded data from: aggregated:customer_emails_aggregated
Shape: (100, 252)
Initialized recommendation registry (Bronze: /Users/Vital/python/CustomerRetention/experiments/runs/email-f00adbd9/data/bronze/customer_emails_aggregated)

## 4.3 Value Range Validation

**📖 Interpretation Guide:**
- **Percentage fields** (rates): Should be 0-100 or 0-1 depending on format
- **Binary fields**: Should only contain 0 and 1
- **Count fields**: Should be non-negative integers
- **Amount fields**: Should be non-negative (unless refunds are possible)

**What to Watch For:**
- Rates > 100% suggest measurement or data entry errors
- Negative values in fields that should be positive
- Binary fields with values other than 0/1

**Actions:**
- Cap rates at 100 if they exceed (or investigate cause)
- Flag records with impossible negative values
- Convert binary fields to proper 0/1 encoding

In [4]:
validator = DataValidator()
range_rules = RuleGenerator.from_findings(findings)

console.start_section()
console.header("Value Range Validation")

if range_rules:
    range_results = validator.validate_value_ranges(df, range_rules)

    issues_found = []
    for r in range_results:
        detail = f"{r.invalid_values} invalid" if r.invalid_values > 0 else None
        console.check(f"{r.column_name} ({r.rule_type})", r.invalid_values == 0, detail)
        if r.invalid_values > 0:
            issues_found.append(r)

    all_invalid = sum(r.invalid_values for r in range_results)
    if all_invalid == 0:
        console.success("All value ranges valid")
    else:
        console.error(f"Found {all_invalid:,} values outside expected ranges")

        console.info("Examples of invalid values:")
        for r in issues_found[:3]:
            col = r.column_name
            if col in df.columns:
                if r.rule_type == 'binary':
                    invalid_mask = ~df[col].isin([0, 1, np.nan])
                    condition = "value not in [0, 1]"
                elif r.rule_type == 'non_negative':
                    invalid_mask = df[col] < 0
                    condition = "value < 0"
                elif r.rule_type == 'percentage':
                    invalid_mask = (df[col] < 0) | (df[col] > 100)
                    condition = "value < 0 or value > 100"
                elif r.rule_type == 'rate':
                    invalid_mask = (df[col] < 0) | (df[col] > 1)
                    condition = "value < 0 or value > 1"
                else:
                    continue

                invalid_values = df.loc[invalid_mask, col].dropna()
                if len(invalid_values) > 0:
                    examples = invalid_values.head(5).tolist()
                    console.metric(f"  {col}", f"{examples}")

                    # Add filtering recommendation
                    registry.add_bronze_filtering(
                        column=col, condition=condition, action="cap",
                        rationale=f"{r.invalid_values} values violate {r.rule_type} constraint",
                        source_notebook="04_column_deep_dive"
                    )

    console.info("Rules auto-generated from detected column types")
else:
    range_results = []
    console.info("No validation rules generated - no binary/numeric columns detected")

console.end_section()

#### VALUE RANGE VALIDATION
[OK] opened_max_180d (binary)
[OK] clicked_sum_180d (binary)
[OK] clicked_max_180d (binary)
[OK] bounced_sum_180d (binary)
[OK] bounced_max_180d (binary)
[OK] opened_max_365d (binary)
[OK] clicked_sum_365d (binary)
[OK] clicked_max_365d (binary)
[OK] bounced_sum_365d (binary)
[OK] bounced_max_365d (binary)
[OK] opened_max_all_time (binary)
[OK] clicked_max_all_time (binary)
[OK] bounced_max_all_time (binary)
[OK] lag0_opened_sum (binary)
[OK] lag0_opened_max (binary)
[OK] lag0_clicked_sum (binary)
[OK] lag0_clicked_max (binary)
[OK] lag0_bounced_sum (binary)
[OK] lag0_bounced_max (binary)
[OK] lag0_time_to_open_hours_count (binary)
[OK] lag1_opened_sum (binary)
[OK] lag1_opened_mean (binary)
[OK] lag1_opened_count (binary)
[OK] lag1_opened_max (binary)
[OK] lag1_clicked_sum (binary)
[OK] lag1_clicked_mean (binary)
[OK] lag1_clicked_count (binary)
[OK] lag1_clicked_max (binary)
[OK] lag1_send_hour_count (binary)
[OK] lag1_bounced_count (binary)
[OK] lag1_time_to_open_hours_count (binary)
[OK] lag1___index_level_0___count (binary)
[OK] lag2_opened_mean (binary)
[OK] lag2_opened_max (binary)
[OK] lag2_clicked_sum (binary)
[OK] lag2_clicked_mean (binary)
[OK] lag2_clicked_max (binary)
[OK] lag3_opened_sum (binary)
[OK] lag3_opened_mean (binary)
[OK] lag3_opened_max (binary)
[OK] lag3_bounced_sum (binary)
[OK] lag3_bounced_mean (binary)
[OK] lag3_bounced_max (binary)
[X] lag3_time_to_open_hours_sum (binary) — 1 invalid
[OK] lag3_time_to_open_hours_count (binary)
[X] opened_velocity_pct (binary) — 3 invalid
[X] clicked_velocity_pct (percentage) — 1 invalid
[X] send_hour_velocity_pct (percentage) — 6 invalid
[X] bounced_velocity (binary) — 1 invalid
[X] time_to_open_hours_velocity_pct (binary) — 4 invalid
[OK] __index_level_0___velocity_pct (percentage)
[X] opened_acceleration (percentage) — 1 invalid
[X] opened_momentum (binary) — 4 invalid
[X] clicked_acceleration (percentage) — 1 invalid
[X] clicked_momentum (binary) — 1 invalid
[X] send_hour_acceleration (percentage) — 1 invalid
[X] bounced_acceleration (binary) — 1 invalid
[X] bounced_momentum (binary) — 1 invalid
[X] time_to_open_hours_acceleration (percentage) — 1 invalid
[X] __index_level_0___acceleration (percentage) — 3 invalid
[OK] opened_trend_ratio (percentage)
[OK] clicked_trend_ratio (percentage)
[OK] send_hour_trend_ratio (percentage)
[OK] bounced_beginning (binary)
[OK] bounced_end (binary)
[OK] bounced_trend_ratio (binary)
[OK] time_to_open_hours_trend_ratio (percentage)
[OK] __index_level_0___trend_ratio (percentage)
[OK] recency_ratio (percentage)
[X] opened_vs_cohort_mean (binary) — 100 invalid
[X] opened_vs_cohort_pct (binary) — 14 invalid
[X] opened_cohort_zscore (binary) — 100 invalid
[X] clicked_vs_cohort_mean (binary) — 100 invalid
[X] clicked_vs_cohort_pct (binary) — 5 invalid
[X] clicked_cohort_zscore (binary) — 100 invalid
[OK] send_hour_vs_cohort_pct (percentage)
[X] bounced_vs_cohort_mean (binary) — 100 invalid
[X] bounced_vs_cohort_pct (binary) — 4 invalid
[X] bounced_cohort_zscore (binary) — 100 invalid
[OK] time_to_open_hours_vs_cohort_pct (percentage)
[OK] __index_level_0___vs_cohort_pct (percentage)
[X] Found 653 values outside expected ranges
*(i) Examples of invalid values:*
  lag3_time_to_open_hours_sum: **[0.1]**
  opened_velocity_pct: **[-1.0, -1.0, -1.0]**
  clicked_velocity_pct: **[-1.0]**
*(i) Rules auto-generated from detected column types*

## 4.4 Numeric Columns Analysis

**📖 How to Interpret These Charts:**
- **Red dashed line** = Mean (sensitive to outliers)
- **Green solid line** = Median (robust to outliers)
- **Large gap between mean and median** = Skewed distribution
- **Long right tail** = Positive skew (common in count/amount data)

**📖 Understanding Distribution Metrics**

| Metric | Interpretation | Action |
|--------|---------------|--------|
| **Skewness** | Measures asymmetry | \|skew\| > 1: Consider log transform |
| **Kurtosis** | Measures tail heaviness | kurt > 10: Cap outliers before transform |
| **Zero %** | Percentage of zeros | > 40%: Use zero-inflation handling |

**📖 Transformation Decision Tree:**
1. If zeros > 40% → Create binary indicator + log(non-zeros)
2. If \|skewness\| > 1 AND kurtosis > 10 → Cap then log
3. If \|skewness\| > 1 → Log transform
4. If kurtosis > 10 → Cap outliers only
5. Otherwise → Standard scaling is sufficient

In [5]:
analyzer = DistributionAnalyzer()

numeric_cols = [
    name for name, col in findings.columns.items()
    if col.inferred_type in [ColumnType.NUMERIC_CONTINUOUS, ColumnType.NUMERIC_DISCRETE]
    and name not in TEMPORAL_METADATA_COLS
]

analyses = analyzer.analyze_dataframe(df, numeric_cols)
recommendations = {col: analyzer.recommend_transformation(analysis)
                   for col, analysis in analyses.items()}

for col_name in numeric_cols:
    col_info = findings.columns[col_name]
    analysis = analyses.get(col_name)
    rec = recommendations.get(col_name)

    print(f"\n{'='*70}")
    print(f"Column: {col_name}")
    print(f"Type: {col_info.inferred_type.value} (Confidence: {col_info.confidence:.0%})")
    print("-" * 70)

    if analysis:
        print("\U0001f4ca Distribution Statistics:")
        print(f"   Mean: {analysis.mean:.3f}  |  Median: {analysis.median:.3f}  |  Std: {analysis.std:.3f}")
        print(f"   Range: [{analysis.min_value:.3f}, {analysis.max_value:.3f}]")
        if analysis.percentiles:
            print(f"   Percentiles: 1%={analysis.percentiles.get('p1', 0):.3f}, 25%={analysis.q1:.3f}, 75%={analysis.q3:.3f}, 99%={analysis.percentiles.get('p99', 0):.3f}")
        print("\n\U0001f4c8 Shape Analysis:")
        skew_label = '(Right-skewed)' if analysis.skewness > 0.5 else '(Left-skewed)' if analysis.skewness < -0.5 else '(Symmetric)'
        print(f"   Skewness: {analysis.skewness:.2f} {skew_label}")
        kurt_label = '(Heavy tails/outliers)' if analysis.kurtosis > 3 else '(Light tails)'
        print(f"   Kurtosis: {analysis.kurtosis:.2f} {kurt_label}")
        print(f"   Zeros: {analysis.zero_count:,} ({analysis.zero_percentage:.1f}%)")
        print(f"   Outliers (IQR): {analysis.outlier_count_iqr:,} ({analysis.outlier_percentage:.1f}%)")

        if rec:
            print(f"\n\U0001f527 Recommended Transformation: {rec.recommended_transform.value}")
            print(f"   Reason: {rec.reason}")
            print(f"   Priority: {rec.priority}")
            if rec.warnings:
                for warn in rec.warnings:
                    print(f"   \u26a0\ufe0f {warn}")

    data = df[col_name].dropna()
    data_np = data.to_numpy()
    fig = go.Figure()

    fig.add_trace(go.Histogram(x=data_np, nbinsx=50, name='Distribution',
                                marker_color='steelblue', opacity=0.7))

    mean_val = float(data.mean())
    median_val = float(data.median())

    mean_position = "top right" if mean_val >= median_val else "top left"
    median_position = "top left" if mean_val >= median_val else "top right"

    fig.add_vline(
        x=mean_val, line_dash="dash", line_color="red",
        annotation_text=f"Mean: {mean_val:.2f}", annotation_position=mean_position,
        annotation_font_color="red", annotation_bgcolor="rgba(255,255,255,0.8)"
    )
    fig.add_vline(
        x=median_val, line_dash="solid", line_color="green",
        annotation_text=f"Median: {median_val:.2f}", annotation_position=median_position,
        annotation_font_color="green", annotation_bgcolor="rgba(255,255,255,0.8)"
    )

    if analysis and analysis.outlier_percentage > 5 and analysis.percentiles.get('p99') is not None:
        fig.add_vline(x=analysis.percentiles['p99'], line_dash="dot", line_color="orange",
                      annotation_text=f"99th: {analysis.percentiles['p99']:.2f}",
                      annotation_position="top right",
                      annotation_font_color="orange",
                      annotation_bgcolor="rgba(255,255,255,0.8)")

    transform_label = rec.recommended_transform.value if rec else "none"
    fig.update_layout(
        title=f"Distribution: {col_name}<br><sub>Skew: {analysis.skewness:.2f} | Kurt: {analysis.kurtosis:.2f} | Strategy: {transform_label}</sub>",
        xaxis_title=col_name, yaxis_title="Count",
        template='plotly_white', height=400
    )
    display_figure(fig)

======================================================================
Column: event_count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.660  |  Median: 0.000  |  Std: 1.121
   Range: [0.000, 6.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=4.020

📈 Shape Analysis:
   Skewness: 2.11 (Right-skewed)
   Kurtosis: 5.28 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.11)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: event_count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.400  |  Median: 1.000  |  Std: 1.886
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.030

📈 Shape Analysis:
   Skewness: 1.84 (Right-skewed)
   Kurtosis: 4.33 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: event_count_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.380  |  Median: 16.000  |  Std: 11.955
   Range: [1.000, 101.000]
   Percentiles: 1%=1.990, 25%=12.000, 75%=20.250, 99%=51.500

📈 Shape Analysis:
   Skewness: 3.68 (Right-skewed)
   Kurtosis: 23.85 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (3.68) with significant outliers (6.0%)
   Priority: high

======================================================================
Column: opened_sum_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.120  |  Median: 0.000  |  Std: 0.409
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 3.60 (Right-skewed)
   Kurtosis: 12.67 (Heavy tails/outliers)
   Zeros: 91 (91.0%)
   Outliers (IQR): 9 (9.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (91.0%) combined with high skewness (3.60)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: opened_mean_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.162  |  Median: 0.000  |  Std: 0.329
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.125, 99%=1.000

📈 Shape Analysis:
   Skewness: 2.01 (Right-skewed)
   Kurtosis: 2.73 (Light tails)
   Zeros: 26 (74.3%)
   Outliers (IQR): 7 (20.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (74.3%) combined with high skewness (2.01)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: opened_count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.660  |  Median: 0.000  |  Std: 1.121
   Range: [0.000, 6.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=4.020

📈 Shape Analysis:
   Skewness: 2.11 (Right-skewed)
   Kurtosis: 5.28 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.11)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: clicked_mean_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.043  |  Median: 0.000  |  Std: 0.128
   Range: [0.000, 0.500]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.500

📈 Shape Analysis:
   Skewness: 3.04 (Right-skewed)
   Kurtosis: 8.47 (Heavy tails/outliers)
   Zeros: 31 (88.6%)
   Outliers (IQR): 4 (11.4%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (88.6%) combined with high skewness (3.04)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: clicked_count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.660  |  Median: 0.000  |  Std: 1.121
   Range: [0.000, 6.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=4.020

📈 Shape Analysis:
   Skewness: 2.11 (Right-skewed)
   Kurtosis: 5.28 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.11)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: send_hour_sum_180d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 8.950  |  Median: 0.000  |  Std: 15.238
   Range: [0.000, 70.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=15.000, 99%=63.070

📈 Shape Analysis:
   Skewness: 2.00 (Right-skewed)
   Kurtosis: 4.04 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 5 (5.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (65.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: send_hour_mean_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 13.771  |  Median: 14.000  |  Std: 3.465
   Range: [6.000, 22.000]
   Percentiles: 1%=7.020, 25%=11.500, 75%=15.625, 99%=21.320

📈 Shape Analysis:
   Skewness: 0.23 (Symmetric)
   Kurtosis: 0.20 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (2.9%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.23)
   Priority: low

======================================================================
Column: send_hour_max_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 15.486  |  Median: 15.000  |  Std: 3.944
   Range: [6.000, 22.000]
   Percentiles: 1%=7.020, 25%=13.500, 75%=18.500, 99%=22.000

📈 Shape Analysis:
   Skewness: -0.35 (Symmetric)
   Kurtosis: -0.28 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.35)
   Priority: low

======================================================================
Column: send_hour_count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.660  |  Median: 0.000  |  Std: 1.121
   Range: [0.000, 6.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=4.020

📈 Shape Analysis:
   Skewness: 2.11 (Right-skewed)
   Kurtosis: 5.28 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.11)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: bounced_mean_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.038  |  Median: 0.000  |  Std: 0.177
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.773

📈 Shape Analysis:
   Skewness: 5.18 (Right-skewed)
   Kurtosis: 27.88 (Heavy tails/outliers)
   Zeros: 33 (94.3%)
   Outliers (IQR): 2 (5.7%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (94.3%) combined with high skewness (5.18)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: bounced_count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.660  |  Median: 0.000  |  Std: 1.121
   Range: [0.000, 6.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=4.020

📈 Shape Analysis:
   Skewness: 2.11 (Right-skewed)
   Kurtosis: 5.28 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.11)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: time_to_open_hours_sum_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.531  |  Median: 0.000  |  Std: 2.861
   Range: [0.000, 26.300]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=10.064

📈 Shape Analysis:
   Skewness: 7.93 (Right-skewed)
   Kurtosis: 68.79 (Heavy tails/outliers)
   Zeros: 91 (91.0%)
   Outliers (IQR): 9 (9.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (91.0%) combined with high skewness (7.93)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: time_to_open_hours_mean_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 3.678  |  Median: 1.900  |  Std: 3.773
   Range: [1.200, 13.150]
   Percentiles: 1%=1.208, 25%=1.800, 75%=4.000, 99%=12.494

📈 Shape Analysis:
   Skewness: 2.41 (Right-skewed)
   Kurtosis: 6.21 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (11.1%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.41) with significant outliers (11.1%)
   Priority: high

======================================================================
Column: time_to_open_hours_max_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 4.656  |  Median: 2.600  |  Std: 5.771
   Range: [1.200, 19.300]
   Percentiles: 1%=1.208, 25%=1.800, 75%=4.000, 99%=18.308

📈 Shape Analysis:
   Skewness: 2.52 (Right-skewed)
   Kurtosis: 6.65 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (11.1%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.52) with significant outliers (11.1%)
   Priority: high

======================================================================
Column: time_to_open_hours_count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.120  |  Median: 0.000  |  Std: 0.409
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 3.60 (Right-skewed)
   Kurtosis: 12.67 (Heavy tails/outliers)
   Zeros: 91 (91.0%)
   Outliers (IQR): 9 (9.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (91.0%) combined with high skewness (3.60)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: __index_level_0___sum_180d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 53920.340  |  Median: 0.000  |  Std: 91450.844
   Range: [0.000, 487367.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=82173.000, 99%=329230.340

📈 Shape Analysis:
   Skewness: 2.10 (Right-skewed)
   Kurtosis: 5.20 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.10)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: __index_level_0___mean_180d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 81808.574  |  Median: 81908.250  |  Std: 697.284
   Range: [80056.000, 83123.000]
   Percentiles: 1%=80152.730, 25%=81508.500, 75%=82144.500, 99%=83102.600

📈 Shape Analysis:
   Skewness: -0.34 (Symmetric)
   Kurtosis: 0.51 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 3 (8.6%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (8.6%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: __index_level_0___max_180d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 82251.171  |  Median: 82254.000  |  Std: 733.468
   Range: [80056.000, 83196.000]
   Percentiles: 1%=80186.900, 25%=81864.000, 75%=82845.000, 99%=83171.180

📈 Shape Analysis:
   Skewness: -1.09 (Left-skewed)
   Kurtosis: 1.49 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (2.9%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.09)
   Priority: medium

======================================================================
Column: __index_level_0___count_180d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.660  |  Median: 0.000  |  Std: 1.121
   Range: [0.000, 6.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=4.020

📈 Shape Analysis:
   Skewness: 2.11 (Right-skewed)
   Kurtosis: 5.28 (Heavy tails/outliers)
   Zeros: 65 (65.0%)
   Outliers (IQR): 7 (7.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (65.0%) combined with high skewness (2.11)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: opened_sum_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.270  |  Median: 0.000  |  Std: 0.617
   Range: [0.000, 3.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.000

📈 Shape Analysis:
   Skewness: 2.65 (Right-skewed)
   Kurtosis: 7.46 (Heavy tails/outliers)
   Zeros: 80 (80.0%)
   Outliers (IQR): 20 (20.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (80.0%) combined with high skewness (2.65)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: opened_mean_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.166  |  Median: 0.000  |  Std: 0.260
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.271, 99%=0.873

📈 Shape Analysis:
   Skewness: 1.49 (Right-skewed)
   Kurtosis: 1.30 (Light tails)
   Zeros: 32 (61.5%)
   Outliers (IQR): 3 (5.8%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (61.5%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: opened_count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.400  |  Median: 1.000  |  Std: 1.886
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.030

📈 Shape Analysis:
   Skewness: 1.84 (Right-skewed)
   Kurtosis: 4.33 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_mean_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.033  |  Median: 0.000  |  Std: 0.099
   Range: [0.000, 0.500]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.415

📈 Shape Analysis:
   Skewness: 3.28 (Right-skewed)
   Kurtosis: 11.02 (Heavy tails/outliers)
   Zeros: 46 (88.5%)
   Outliers (IQR): 6 (11.5%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (88.5%) combined with high skewness (3.28)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: clicked_count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.400  |  Median: 1.000  |  Std: 1.886
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.030

📈 Shape Analysis:
   Skewness: 1.84 (Right-skewed)
   Kurtosis: 4.33 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: send_hour_sum_365d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 18.960  |  Median: 9.000  |  Std: 25.678
   Range: [0.000, 118.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=30.250, 99%=104.140

📈 Shape Analysis:
   Skewness: 1.65 (Right-skewed)
   Kurtosis: 2.67 (Light tails)
   Zeros: 48 (48.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: send_hour_mean_365d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 13.448  |  Median: 13.583  |  Std: 2.687
   Range: [6.000, 22.000]
   Percentiles: 1%=7.020, 25%=12.000, 75%=15.000, 99%=19.450

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 1.67 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (3.8%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.00)
   Priority: low

======================================================================
Column: send_hour_max_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 15.788  |  Median: 16.000  |  Std: 3.472
   Range: [6.000, 22.000]
   Percentiles: 1%=7.020, 25%=14.000, 75%=18.000, 99%=22.000

📈 Shape Analysis:
   Skewness: -0.46 (Symmetric)
   Kurtosis: 0.29 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (1.9%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.46)
   Priority: low

======================================================================
Column: send_hour_count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.400  |  Median: 1.000  |  Std: 1.886
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.030

📈 Shape Analysis:
   Skewness: 1.84 (Right-skewed)
   Kurtosis: 4.33 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: bounced_mean_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.036  |  Median: 0.000  |  Std: 0.157
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.745

📈 Shape Analysis:
   Skewness: 5.24 (Right-skewed)
   Kurtosis: 29.51 (Heavy tails/outliers)
   Zeros: 48 (92.3%)
   Outliers (IQR): 4 (7.7%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (92.3%) combined with high skewness (5.24)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: bounced_count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.400  |  Median: 1.000  |  Std: 1.886
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.030

📈 Shape Analysis:
   Skewness: 1.84 (Right-skewed)
   Kurtosis: 4.33 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: time_to_open_hours_sum_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.208  |  Median: 0.000  |  Std: 3.930
   Range: [0.000, 31.300]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=14.866

📈 Shape Analysis:
   Skewness: 5.40 (Right-skewed)
   Kurtosis: 36.05 (Heavy tails/outliers)
   Zeros: 80 (80.0%)
   Outliers (IQR): 20 (20.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (80.0%) combined with high skewness (5.40)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: time_to_open_hours_mean_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 4.214  |  Median: 2.900  |  Std: 3.764
   Range: [0.400, 14.700]
   Percentiles: 1%=0.457, 25%=1.725, 75%=5.200, 99%=13.889

📈 Shape Analysis:
   Skewness: 1.49 (Right-skewed)
   Kurtosis: 1.90 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (10.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.49)
   Priority: medium

======================================================================
Column: time_to_open_hours_max_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 4.895  |  Median: 3.200  |  Std: 4.873
   Range: [0.400, 19.300]
   Percentiles: 1%=0.457, 25%=1.725, 75%=5.850, 99%=18.426

📈 Shape Analysis:
   Skewness: 1.85 (Right-skewed)
   Kurtosis: 3.41 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (10.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.85)
   Priority: medium

======================================================================
Column: time_to_open_hours_count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.270  |  Median: 0.000  |  Std: 0.617
   Range: [0.000, 3.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.000

📈 Shape Analysis:
   Skewness: 2.65 (Right-skewed)
   Kurtosis: 7.46 (Heavy tails/outliers)
   Zeros: 80 (80.0%)
   Outliers (IQR): 20 (20.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (80.0%) combined with high skewness (2.65)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: __index_level_0___sum_365d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 111948.180  |  Median: 77229.000  |  Std: 151170.490
   Range: [0.000, 804567.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=161389.750, 99%=559867.710

📈 Shape Analysis:
   Skewness: 1.85 (Right-skewed)
   Kurtosis: 4.39 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: __index_level_0___mean_365d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 79815.283  |  Median: 80069.667  |  Std: 1506.622
   Range: [76848.500, 82993.000]
   Percentiles: 1%=76896.695, 25%=79214.125, 75%=80698.417, 99%=82561.030

📈 Shape Analysis:
   Skewness: -0.39 (Symmetric)
   Kurtosis: -0.43 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 3 (5.8%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (5.8%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: __index_level_0___max_365d
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 80944.923  |  Median: 81864.000  |  Std: 2070.267
   Range: [76943.000, 83196.000]
   Percentiles: 1%=76982.780, 25%=79300.750, 75%=82684.000, 99%=83158.770

📈 Shape Analysis:
   Skewness: -0.76 (Left-skewed)
   Kurtosis: -0.95 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.76)
   Priority: low

======================================================================
Column: __index_level_0___count_365d
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.400  |  Median: 1.000  |  Std: 1.886
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.030

📈 Shape Analysis:
   Skewness: 1.84 (Right-skewed)
   Kurtosis: 4.33 (Heavy tails/outliers)
   Zeros: 48 (48.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (48.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: opened_sum_all_time
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 4.050  |  Median: 4.000  |  Std: 3.978
   Range: [0.000, 33.000]
   Percentiles: 1%=0.000, 25%=2.000, 75%=5.250, 99%=11.220

📈 Shape Analysis:
   Skewness: 3.99 (Right-skewed)
   Kurtosis: 27.58 (Heavy tails/outliers)
   Zeros: 17 (17.0%)
   Outliers (IQR): 2 (2.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: High skewness (3.99) with non-positive values
   Priority: high

======================================================================
Column: opened_mean_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.201  |  Median: 0.211  |  Std: 0.125
   Range: [0.000, 0.500]
   Percentiles: 1%=0.000, 25%=0.125, 75%=0.278, 99%=0.445

📈 Shape Analysis:
   Skewness: -0.05 (Symmetric)
   Kurtosis: -0.47 (Light tails)
   Zeros: 17 (17.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.05)
   Priority: low

======================================================================
Column: opened_count_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.380  |  Median: 16.000  |  Std: 11.955
   Range: [1.000, 101.000]
   Percentiles: 1%=1.990, 25%=12.000, 75%=20.250, 99%=51.500

📈 Shape Analysis:
   Skewness: 3.68 (Right-skewed)
   Kurtosis: 23.85 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (3.68) with significant outliers (6.0%)
   Priority: high

======================================================================
Column: clicked_sum_all_time
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.160  |  Median: 1.000  |  Std: 1.461
   Range: [0.000, 9.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=8.010

📈 Shape Analysis:
   Skewness: 2.81 (Right-skewed)
   Kurtosis: 11.81 (Heavy tails/outliers)
   Zeros: 38 (38.0%)
   Outliers (IQR): 2 (2.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (38.0%) combined with high skewness (2.81)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: clicked_mean_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.057  |  Median: 0.059  |  Std: 0.056
   Range: [0.000, 0.200]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.091, 99%=0.200

📈 Shape Analysis:
   Skewness: 0.64 (Right-skewed)
   Kurtosis: -0.42 (Light tails)
   Zeros: 38 (38.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (38.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_count_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.380  |  Median: 16.000  |  Std: 11.955
   Range: [1.000, 101.000]
   Percentiles: 1%=1.990, 25%=12.000, 75%=20.250, 99%=51.500

📈 Shape Analysis:
   Skewness: 3.68 (Right-skewed)
   Kurtosis: 23.85 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (3.68) with significant outliers (6.0%)
   Priority: high

======================================================================
Column: send_hour_sum_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 235.070  |  Median: 225.000  |  Std: 156.799
   Range: [13.000, 1289.000]
   Percentiles: 1%=28.840, 25%=162.750, 75%=285.250, 99%=703.910

📈 Shape Analysis:
   Skewness: 3.32 (Right-skewed)
   Kurtosis: 20.31 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 5 (5.0%)

🔧 Recommended Transformation: log_transform
   Reason: High positive skewness (3.32) with all positive values
   Priority: high

======================================================================
Column: send_hour_mean_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 13.584  |  Median: 13.620  |  Std: 1.014
   Range: [11.118, 16.118]
   Percentiles: 1%=11.595, 25%=12.944, 75%=14.115, 99%=16.001

📈 Shape Analysis:
   Skewness: 0.30 (Symmetric)
   Kurtosis: 0.24 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.30)
   Priority: low

======================================================================
Column: send_hour_max_all_time
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 19.860  |  Median: 20.000  |  Std: 1.995
   Range: [13.000, 22.000]
   Percentiles: 1%=13.990, 25%=19.000, 75%=21.250, 99%=22.000

📈 Shape Analysis:
   Skewness: -1.08 (Left-skewed)
   Kurtosis: 1.06 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.08)
   Priority: medium

======================================================================
Column: send_hour_count_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.380  |  Median: 16.000  |  Std: 11.955
   Range: [1.000, 101.000]
   Percentiles: 1%=1.990, 25%=12.000, 75%=20.250, 99%=51.500

📈 Shape Analysis:
   Skewness: 3.68 (Right-skewed)
   Kurtosis: 23.85 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (3.68) with significant outliers (6.0%)
   Priority: high

======================================================================
Column: bounced_sum_all_time
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.280  |  Median: 0.000  |  Std: 0.570
   Range: [0.000, 3.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.010

📈 Shape Analysis:
   Skewness: 2.27 (Right-skewed)
   Kurtosis: 5.71 (Heavy tails/outliers)
   Zeros: 77 (77.0%)
   Outliers (IQR): 23 (23.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (77.0%) combined with high skewness (2.27)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: bounced_mean_all_time
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.015  |  Median: 0.000  |  Std: 0.034
   Range: [0.000, 0.182]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.143

📈 Shape Analysis:
   Skewness: 2.61 (Right-skewed)
   Kurtosis: 7.55 (Heavy tails/outliers)
   Zeros: 77 (77.0%)
   Outliers (IQR): 23 (23.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (77.0%) combined with high skewness (2.61)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: bounced_count_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.380  |  Median: 16.000  |  Std: 11.955
   Range: [1.000, 101.000]
   Percentiles: 1%=1.990, 25%=12.000, 75%=20.250, 99%=51.500

📈 Shape Analysis:
   Skewness: 3.68 (Right-skewed)
   Kurtosis: 23.85 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (3.68) with significant outliers (6.0%)
   Priority: high

======================================================================
Column: time_to_open_hours_sum_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 15.419  |  Median: 12.600  |  Std: 19.026
   Range: [0.000, 160.000]
   Percentiles: 1%=0.000, 25%=3.225, 75%=21.950, 99%=65.752

📈 Shape Analysis:
   Skewness: 4.73 (Right-skewed)
   Kurtosis: 33.50 (Heavy tails/outliers)
   Zeros: 18 (18.0%)
   Outliers (IQR): 2 (2.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: High skewness (4.73) with non-positive values
   Priority: high

======================================================================
Column: time_to_open_hours_mean_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 3.633  |  Median: 3.400  |  Std: 1.753
   Range: [0.000, 8.300]
   Percentiles: 1%=0.328, 25%=2.590, 75%=4.667, 99%=7.999

📈 Shape Analysis:
   Skewness: 0.47 (Symmetric)
   Kurtosis: 0.15 (Light tails)
   Zeros: 1 (1.2%)
   Outliers (IQR): 2 (2.4%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.47)
   Priority: low

======================================================================
Column: time_to_open_hours_max_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 8.071  |  Median: 7.400  |  Std: 4.767
   Range: [0.000, 19.500]
   Percentiles: 1%=0.328, 25%=4.650, 75%=10.400, 99%=19.336

📈 Shape Analysis:
   Skewness: 0.56 (Right-skewed)
   Kurtosis: -0.29 (Light tails)
   Zeros: 1 (1.2%)
   Outliers (IQR): 2 (2.4%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.56)
   Priority: low

======================================================================
Column: time_to_open_hours_count_all_time
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 4.050  |  Median: 4.000  |  Std: 3.978
   Range: [0.000, 33.000]
   Percentiles: 1%=0.000, 25%=2.000, 75%=5.250, 99%=11.220

📈 Shape Analysis:
   Skewness: 3.99 (Right-skewed)
   Kurtosis: 27.58 (Heavy tails/outliers)
   Zeros: 17 (17.0%)
   Outliers (IQR): 2 (2.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: High skewness (3.99) with non-positive values
   Priority: high

======================================================================
Column: __index_level_0___sum_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 707278.670  |  Median: 755625.500  |  Std: 597235.212
   Range: [9080.000, 4818780.000]
   Percentiles: 1%=16437.680, 25%=301376.250, 75%=915203.500, 99%=2468659.590

📈 Shape Analysis:
   Skewness: 3.46 (Right-skewed)
   Kurtosis: 22.24 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (2.0%)

🔧 Recommended Transformation: log_transform
   Reason: High positive skewness (3.46) with all positive values
   Priority: high

======================================================================
Column: __index_level_0___mean_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 36711.591  |  Median: 42556.010  |  Std: 14562.999
   Range: [3564.148, 56828.176]
   Percentiles: 1%=3831.384, 25%=25283.068, 75%=47790.828, 99%=56371.550

📈 Shape Analysis:
   Skewness: -0.76 (Left-skewed)
   Kurtosis: -0.56 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.76)
   Priority: low

======================================================================
Column: __index_level_0___max_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 62948.270  |  Median: 77026.500  |  Std: 24189.590
   Range: [7757.000, 83196.000]
   Percentiles: 1%=8011.430, 25%=43273.750, 75%=81947.250, 99%=83123.730

📈 Shape Analysis:
   Skewness: -1.04 (Left-skewed)
   Kurtosis: -0.30 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.04)
   Priority: medium

======================================================================
Column: __index_level_0___count_all_time
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.380  |  Median: 16.000  |  Std: 11.955
   Range: [1.000, 101.000]
   Percentiles: 1%=1.990, 25%=12.000, 75%=20.250, 99%=51.500

📈 Shape Analysis:
   Skewness: 3.68 (Right-skewed)
   Kurtosis: 23.85 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 6 (6.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (3.68) with significant outliers (6.0%)
   Priority: high

======================================================================
Column: days_since_last_event_x
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 925.910  |  Median: 342.000  |  Std: 1028.318
   Range: [0.000, 3076.000]
   Percentiles: 1%=3.960, 25%=73.250, 75%=1877.000, 99%=3069.070

📈 Shape Analysis:
   Skewness: 0.86 (Right-skewed)
   Kurtosis: -0.75 (Light tails)
   Zeros: 1 (1.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.86)
   Priority: low

======================================================================
Column: days_since_first_event_x
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 3149.480  |  Median: 3223.500  |  Std: 147.566
   Range: [2657.000, 3285.000]
   Percentiles: 1%=2707.490, 25%=3079.000, 75%=3254.750, 99%=3284.010

📈 Shape Analysis:
   Skewness: -1.39 (Left-skewed)
   Kurtosis: 1.25 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.39)
   Priority: medium

======================================================================
Column: lag0_opened_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.113  |  Median: 0.000  |  Std: 0.298
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=1.000

📈 Shape Analysis:
   Skewness: 2.49 (Right-skewed)
   Kurtosis: 4.64 (Heavy tails/outliers)
   Zeros: 86 (86.0%)
   Outliers (IQR): 14 (14.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (86.0%) combined with high skewness (2.49)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag0_opened_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.250  |  Median: 1.000  |  Std: 0.520
   Range: [1.000, 4.000]
   Percentiles: 1%=1.000, 25%=1.000, 75%=1.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 2.45 (Right-skewed)
   Kurtosis: 7.67 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 22 (22.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.45) with significant outliers (22.0%)
   Priority: high

======================================================================
Column: lag0_clicked_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.028  |  Median: 0.000  |  Std: 0.132
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.505

📈 Shape Analysis:
   Skewness: 5.52 (Right-skewed)
   Kurtosis: 33.40 (Heavy tails/outliers)
   Zeros: 95 (95.0%)
   Outliers (IQR): 5 (5.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (95.0%) combined with high skewness (5.52)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag0_clicked_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.250  |  Median: 1.000  |  Std: 0.520
   Range: [1.000, 4.000]
   Percentiles: 1%=1.000, 25%=1.000, 75%=1.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 2.45 (Right-skewed)
   Kurtosis: 7.67 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 22 (22.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.45) with significant outliers (22.0%)
   Priority: high

======================================================================
Column: lag0_send_hour_sum
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.620  |  Median: 15.000  |  Std: 8.053
   Range: [6.000, 51.000]
   Percentiles: 1%=6.990, 25%=12.750, 75%=20.000, 99%=38.130

📈 Shape Analysis:
   Skewness: 1.47 (Right-skewed)
   Kurtosis: 2.50 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 8 (8.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.47)
   Priority: medium

======================================================================
Column: lag0_send_hour_mean
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 14.111  |  Median: 14.000  |  Std: 3.321
   Range: [6.000, 22.000]
   Percentiles: 1%=6.990, 25%=12.000, 75%=16.000, 99%=20.020

📈 Shape Analysis:
   Skewness: -0.05 (Symmetric)
   Kurtosis: -0.42 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.05)
   Priority: low

======================================================================
Column: lag0_send_hour_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.250  |  Median: 1.000  |  Std: 0.520
   Range: [1.000, 4.000]
   Percentiles: 1%=1.000, 25%=1.000, 75%=1.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 2.45 (Right-skewed)
   Kurtosis: 7.67 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 22 (22.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.45) with significant outliers (22.0%)
   Priority: high

======================================================================
Column: lag0_send_hour_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 14.830  |  Median: 15.000  |  Std: 3.674
   Range: [6.000, 22.000]
   Percentiles: 1%=6.990, 25%=12.000, 75%=18.000, 99%=22.000

📈 Shape Analysis:
   Skewness: -0.16 (Symmetric)
   Kurtosis: -0.67 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.16)
   Priority: low

======================================================================
Column: lag0_bounced_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.030  |  Median: 0.000  |  Std: 0.156
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=1.000

📈 Shape Analysis:
   Skewness: 5.51 (Right-skewed)
   Kurtosis: 30.74 (Heavy tails/outliers)
   Zeros: 96 (96.0%)
   Outliers (IQR): 4 (4.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (96.0%) combined with high skewness (5.51)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag0_bounced_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.250  |  Median: 1.000  |  Std: 0.520
   Range: [1.000, 4.000]
   Percentiles: 1%=1.000, 25%=1.000, 75%=1.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 2.45 (Right-skewed)
   Kurtosis: 7.67 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 22 (22.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.45) with significant outliers (22.0%)
   Priority: high

======================================================================
Column: lag0_time_to_open_hours_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.736  |  Median: 0.000  |  Std: 2.765
   Range: [0.000, 19.300]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=14.746

📈 Shape Analysis:
   Skewness: 5.04 (Right-skewed)
   Kurtosis: 27.56 (Heavy tails/outliers)
   Zeros: 86 (86.0%)
   Outliers (IQR): 14 (14.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (86.0%) combined with high skewness (5.04)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag0_time_to_open_hours_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 5.257  |  Median: 2.800  |  Std: 5.713
   Range: [0.400, 19.300]
   Percentiles: 1%=0.504, 25%=1.800, 75%=7.500, 99%=18.702

📈 Shape Analysis:
   Skewness: 1.60 (Right-skewed)
   Kurtosis: 1.77 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (7.1%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.60)
   Priority: medium

======================================================================
Column: lag0_time_to_open_hours_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 5.257  |  Median: 2.800  |  Std: 5.713
   Range: [0.400, 19.300]
   Percentiles: 1%=0.504, 25%=1.800, 75%=7.500, 99%=18.702

📈 Shape Analysis:
   Skewness: 1.60 (Right-skewed)
   Kurtosis: 1.77 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (7.1%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.60)
   Priority: medium

======================================================================
Column: lag0___index_level_0___sum
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 76310.540  |  Median: 79450.500  |  Std: 39891.718
   Range: [8797.000, 165655.000]
   Percentiles: 1%=9077.170, 25%=46086.000, 75%=82814.500, 99%=165201.580

📈 Shape Analysis:
   Skewness: 0.67 (Right-skewed)
   Kurtosis: 0.19 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 13 (13.0%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (13.0%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: lag0___index_level_0___mean
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 62904.692  |  Median: 76895.750  |  Std: 24218.768
   Range: [7177.667, 83196.000]
   Percentiles: 1%=7490.837, 25%=43246.375, 75%=81947.250, 99%=83123.730

📈 Shape Analysis:
   Skewness: -1.04 (Left-skewed)
   Kurtosis: -0.29 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.04)
   Priority: medium

======================================================================
Column: lag0___index_level_0___count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.250  |  Median: 1.000  |  Std: 0.520
   Range: [1.000, 4.000]
   Percentiles: 1%=1.000, 25%=1.000, 75%=1.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 2.45 (Right-skewed)
   Kurtosis: 7.67 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 22 (22.0%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.45) with significant outliers (22.0%)
   Priority: high

======================================================================
Column: lag0___index_level_0___max
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 62948.270  |  Median: 77026.500  |  Std: 24189.590
   Range: [7757.000, 83196.000]
   Percentiles: 1%=8011.430, 25%=43273.750, 75%=81947.250, 99%=83123.730

📈 Shape Analysis:
   Skewness: -1.04 (Left-skewed)
   Kurtosis: -0.30 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.04)
   Priority: medium

======================================================================
Column: lag1_send_hour_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 14.053  |  Median: 15.000  |  Std: 3.597
   Range: [7.000, 20.000]
   Percentiles: 1%=7.360, 25%=12.500, 75%=16.500, 99%=19.820

📈 Shape Analysis:
   Skewness: -0.39 (Symmetric)
   Kurtosis: -0.46 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.39)
   Priority: low

======================================================================
Column: lag1_send_hour_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 14.053  |  Median: 15.000  |  Std: 3.597
   Range: [7.000, 20.000]
   Percentiles: 1%=7.360, 25%=12.500, 75%=16.500, 99%=19.820

📈 Shape Analysis:
   Skewness: -0.39 (Symmetric)
   Kurtosis: -0.46 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.39)
   Priority: low

======================================================================
Column: lag1_send_hour_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 14.053  |  Median: 15.000  |  Std: 3.597
   Range: [7.000, 20.000]
   Percentiles: 1%=7.360, 25%=12.500, 75%=16.500, 99%=19.820

📈 Shape Analysis:
   Skewness: -0.39 (Symmetric)
   Kurtosis: -0.46 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.39)
   Priority: low

======================================================================
Column: lag1_bounced_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 19 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag1_bounced_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 19 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag1_bounced_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 19 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag1_time_to_open_hours_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.068  |  Median: 0.000  |  Std: 2.198
   Range: [0.000, 7.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=6.658

📈 Shape Analysis:
   Skewness: 1.82 (Right-skewed)
   Kurtosis: 2.05 (Light tails)
   Zeros: 15 (78.9%)
   Outliers (IQR): 4 (21.1%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (78.9%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag1_time_to_open_hours_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 5.075  |  Median: 4.650  |  Std: 1.370
   Range: [4.000, 7.000]
   Percentiles: 1%=4.006, 25%=4.150, 75%=5.575, 99%=6.943

📈 Shape Analysis:
   Skewness: 1.35 (Right-skewed)
   Kurtosis: 1.33 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.35)
   Priority: medium

======================================================================
Column: lag1_time_to_open_hours_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 5.075  |  Median: 4.650  |  Std: 1.370
   Range: [4.000, 7.000]
   Percentiles: 1%=4.006, 25%=4.150, 75%=5.575, 99%=6.943

📈 Shape Analysis:
   Skewness: 1.35 (Right-skewed)
   Kurtosis: 1.33 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.35)
   Priority: medium

======================================================================
Column: lag1___index_level_0___sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 57803.053  |  Median: 71966.000  |  Std: 28338.818
   Range: [6172.000, 82167.000]
   Percentiles: 1%=6378.820, 25%=40561.000, 75%=79964.500, 99%=82144.320

📈 Shape Analysis:
   Skewness: -0.94 (Left-skewed)
   Kurtosis: -0.77 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.94)
   Priority: low

======================================================================
Column: lag1___index_level_0___mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 57803.053  |  Median: 71966.000  |  Std: 28338.818
   Range: [6172.000, 82167.000]
   Percentiles: 1%=6378.820, 25%=40561.000, 75%=79964.500, 99%=82144.320

📈 Shape Analysis:
   Skewness: -0.94 (Left-skewed)
   Kurtosis: -0.77 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.94)
   Priority: low

======================================================================
Column: lag1___index_level_0___max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 57803.053  |  Median: 71966.000  |  Std: 28338.818
   Range: [6172.000, 82167.000]
   Percentiles: 1%=6378.820, 25%=40561.000, 75%=79964.500, 99%=82144.320

📈 Shape Analysis:
   Skewness: -0.94 (Left-skewed)
   Kurtosis: -0.77 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.94)
   Priority: low

======================================================================
Column: lag2_opened_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.222  |  Median: 0.000  |  Std: 0.548
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=1.830

📈 Shape Analysis:
   Skewness: 2.57 (Right-skewed)
   Kurtosis: 6.36 (Heavy tails/outliers)
   Zeros: 15 (83.3%)
   Outliers (IQR): 3 (16.7%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (83.3%) combined with high skewness (2.57)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_opened_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.260  |  Median: 0.000  |  Std: 0.661
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 3.30 (Right-skewed)
   Kurtosis: 12.87 (Heavy tails/outliers)
   Zeros: 82 (82.0%)
   Outliers (IQR): 18 (18.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (82.0%) combined with high skewness (3.30)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_clicked_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.260  |  Median: 0.000  |  Std: 0.661
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 3.30 (Right-skewed)
   Kurtosis: 12.87 (Heavy tails/outliers)
   Zeros: 82 (82.0%)
   Outliers (IQR): 18 (18.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (82.0%) combined with high skewness (3.30)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_send_hour_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 17.556  |  Median: 13.500  |  Std: 12.876
   Range: [6.000, 60.000]
   Percentiles: 1%=6.340, 25%=9.500, 75%=19.250, 99%=55.580

📈 Shape Analysis:
   Skewness: 2.39 (Right-skewed)
   Kurtosis: 6.69 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (11.1%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.39) with significant outliers (11.1%)
   Priority: high

======================================================================
Column: lag2_send_hour_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 11.824  |  Median: 11.417  |  Std: 3.088
   Range: [6.000, 17.000]
   Percentiles: 1%=6.340, 25%=9.250, 75%=14.000, 99%=17.000

📈 Shape Analysis:
   Skewness: 0.08 (Symmetric)
   Kurtosis: -0.61 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.08)
   Priority: low

======================================================================
Column: lag2_send_hour_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.260  |  Median: 0.000  |  Std: 0.661
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 3.30 (Right-skewed)
   Kurtosis: 12.87 (Heavy tails/outliers)
   Zeros: 82 (82.0%)
   Outliers (IQR): 18 (18.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (82.0%) combined with high skewness (3.30)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_send_hour_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 12.722  |  Median: 12.500  |  Std: 3.878
   Range: [6.000, 21.000]
   Percentiles: 1%=6.340, 25%=9.500, 75%=15.000, 99%=20.320

📈 Shape Analysis:
   Skewness: 0.28 (Symmetric)
   Kurtosis: -0.31 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.28)
   Priority: low

======================================================================
Column: lag2_bounced_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 18 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag2_bounced_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 18 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag2_bounced_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.260  |  Median: 0.000  |  Std: 0.661
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 3.30 (Right-skewed)
   Kurtosis: 12.87 (Heavy tails/outliers)
   Zeros: 82 (82.0%)
   Outliers (IQR): 18 (18.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (82.0%) combined with high skewness (3.30)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_bounced_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 18 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag2_time_to_open_hours_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.672  |  Median: 0.000  |  Std: 1.830
   Range: [0.000, 6.900]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=6.407

📈 Shape Analysis:
   Skewness: 2.96 (Right-skewed)
   Kurtosis: 8.58 (Heavy tails/outliers)
   Zeros: 15 (83.3%)
   Outliers (IQR): 3 (16.7%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (83.3%) combined with high skewness (2.96)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_time_to_open_hours_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 3.367  |  Median: 2.000  |  Std: 3.086
   Range: [1.200, 6.900]
   Percentiles: 1%=1.216, 25%=1.600, 75%=4.450, 99%=6.802

📈 Shape Analysis:
   Skewness: 1.60 (Right-skewed)
   Kurtosis: nan (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.60)
   Priority: medium

======================================================================
Column: lag2_time_to_open_hours_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.040  |  Median: 0.000  |  Std: 0.243
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=1.010

📈 Shape Analysis:
   Skewness: 6.69 (Right-skewed)
   Kurtosis: 47.66 (Heavy tails/outliers)
   Zeros: 97 (97.0%)
   Outliers (IQR): 3 (3.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (97.0%) combined with high skewness (6.69)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2_time_to_open_hours_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 3.733  |  Median: 3.100  |  Std: 2.902
   Range: [1.200, 6.900]
   Percentiles: 1%=1.238, 25%=2.150, 75%=5.000, 99%=6.824

📈 Shape Analysis:
   Skewness: 0.94 (Right-skewed)
   Kurtosis: nan (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.94)
   Priority: low

======================================================================
Column: lag2___index_level_0___sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 74024.611  |  Median: 78480.000  |  Std: 46155.293
   Range: [6307.000, 163181.000]
   Percentiles: 1%=8186.180, 25%=43103.000, 75%=81446.750, 99%=162603.510

📈 Shape Analysis:
   Skewness: 0.70 (Right-skewed)
   Kurtosis: 0.06 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 3 (16.7%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (16.7%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: lag2___index_level_0___mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 59234.681  |  Median: 76407.500  |  Std: 29183.180
   Range: [5714.750, 81590.500]
   Percentiles: 1%=5727.033, 25%=43103.000, 75%=80883.250, 99%=81588.035

📈 Shape Analysis:
   Skewness: -1.07 (Left-skewed)
   Kurtosis: -0.45 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.07)
   Priority: medium

======================================================================
Column: lag2___index_level_0___count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.260  |  Median: 0.000  |  Std: 0.661
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.010

📈 Shape Analysis:
   Skewness: 3.30 (Right-skewed)
   Kurtosis: 12.87 (Heavy tails/outliers)
   Zeros: 82 (82.0%)
   Outliers (IQR): 18 (18.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (82.0%) combined with high skewness (3.30)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: lag2___index_level_0___max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 59291.278  |  Median: 76513.000  |  Std: 29146.982
   Range: [5908.000, 81770.000]
   Percentiles: 1%=5943.020, 25%=43103.000, 75%=80883.250, 99%=81737.020

📈 Shape Analysis:
   Skewness: -1.06 (Left-skewed)
   Kurtosis: -0.45 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (-1.06)
   Priority: medium

======================================================================
Column: lag3_opened_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.230  |  Median: 0.000  |  Std: 0.468
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 1.89 (Right-skewed)
   Kurtosis: 2.83 (Light tails)
   Zeros: 79 (79.0%)
   Outliers (IQR): 21 (21.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (79.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_clicked_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 21 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_clicked_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 21 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_clicked_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.230  |  Median: 0.000  |  Std: 0.468
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 1.89 (Right-skewed)
   Kurtosis: 2.83 (Light tails)
   Zeros: 79 (79.0%)
   Outliers (IQR): 21 (21.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (79.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_clicked_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 21 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_send_hour_sum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 13.810  |  Median: 13.000  |  Std: 5.446
   Range: [6.000, 26.000]
   Percentiles: 1%=6.000, 25%=10.000, 75%=16.000, 99%=25.400

📈 Shape Analysis:
   Skewness: 0.65 (Right-skewed)
   Kurtosis: -0.08 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (4.8%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.65)
   Priority: low

======================================================================
Column: lag3_send_hour_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 12.643  |  Median: 12.000  |  Std: 4.108
   Range: [6.000, 22.000]
   Percentiles: 1%=6.000, 25%=10.000, 75%=15.000, 99%=21.400

📈 Shape Analysis:
   Skewness: 0.42 (Symmetric)
   Kurtosis: 0.07 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.42)
   Priority: low

======================================================================
Column: lag3_send_hour_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.230  |  Median: 0.000  |  Std: 0.468
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 1.89 (Right-skewed)
   Kurtosis: 2.83 (Light tails)
   Zeros: 79 (79.0%)
   Outliers (IQR): 21 (21.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (79.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_send_hour_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 12.952  |  Median: 13.000  |  Std: 4.213
   Range: [6.000, 22.000]
   Percentiles: 1%=6.000, 25%=10.000, 75%=16.000, 99%=21.400

📈 Shape Analysis:
   Skewness: 0.21 (Symmetric)
   Kurtosis: -0.31 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.21)
   Priority: low

======================================================================
Column: lag3_bounced_count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.230  |  Median: 0.000  |  Std: 0.468
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 1.89 (Right-skewed)
   Kurtosis: 2.83 (Light tails)
   Zeros: 79 (79.0%)
   Outliers (IQR): 21 (21.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (79.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3_time_to_open_hours_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.100  |  Median: 0.100  |  Std: nan
   Range: [0.100, 0.100]
   Percentiles: 1%=0.100, 25%=0.100, 75%=0.100, 99%=0.100

📈 Shape Analysis:
   Skewness: nan (Symmetric)
   Kurtosis: nan (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: nan)
   Priority: low

======================================================================
Column: lag3_time_to_open_hours_max
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.100  |  Median: 0.100  |  Std: nan
   Range: [0.100, 0.100]
   Percentiles: 1%=0.100, 25%=0.100, 75%=0.100, 99%=0.100

📈 Shape Analysis:
   Skewness: nan (Symmetric)
   Kurtosis: nan (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: nan)
   Priority: low

======================================================================
Column: lag3___index_level_0___sum
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 57365.952  |  Median: 66385.000  |  Std: 36635.419
   Range: [3679.000, 162460.000]
   Percentiles: 1%=3821.800, 25%=30556.000, 75%=80281.000, 99%=146191.800

📈 Shape Analysis:
   Skewness: 0.80 (Right-skewed)
   Kurtosis: 2.08 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (4.8%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.80)
   Priority: low

======================================================================
Column: lag3___index_level_0___mean
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 53275.905  |  Median: 66385.000  |  Std: 28710.716
   Range: [3679.000, 81230.000]
   Percentiles: 1%=3821.800, 25%=30556.000, 75%=80281.000, 99%=81207.800

📈 Shape Analysis:
   Skewness: -0.63 (Left-skewed)
   Kurtosis: -1.15 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.63)
   Priority: low

======================================================================
Column: lag3___index_level_0___count
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.230  |  Median: 0.000  |  Std: 0.468
   Range: [0.000, 2.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=2.000

📈 Shape Analysis:
   Skewness: 1.89 (Right-skewed)
   Kurtosis: 2.83 (Light tails)
   Zeros: 79 (79.0%)
   Outliers (IQR): 21 (21.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (79.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: lag3___index_level_0___max
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 53297.810  |  Median: 66385.000  |  Std: 28672.716
   Range: [3679.000, 81236.000]
   Percentiles: 1%=3821.800, 25%=30556.000, 75%=80281.000, 99%=81212.600

📈 Shape Analysis:
   Skewness: -0.63 (Left-skewed)
   Kurtosis: -1.16 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.63)
   Priority: low

======================================================================
Column: opened_velocity
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.002  |  Median: 0.000  |  Std: 0.021
   Range: [-0.033, 0.033]
   Percentiles: 1%=-0.033, 25%=0.000, 75%=0.000, 99%=0.033

📈 Shape Analysis:
   Skewness: -0.03 (Symmetric)
   Kurtosis: 0.02 (Light tails)
   Zeros: 12 (63.2%)
   Outliers (IQR): 7 (36.8%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (63.2%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_velocity
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.011
   Range: [-0.033, 0.033]
   Percentiles: 1%=-0.027, 25%=0.000, 75%=0.000, 99%=0.027

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 9.00 (Heavy tails/outliers)
   Zeros: 17 (89.5%)
   Outliers (IQR): 2 (10.5%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (89.5%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_velocity_pct
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: -1.000  |  Median: -1.000  |  Std: nan
   Range: [-1.000, -1.000]
   Percentiles: 1%=-1.000, 25%=-1.000, 75%=-1.000, 99%=-1.000

📈 Shape Analysis:
   Skewness: nan (Symmetric)
   Kurtosis: nan (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: nan)
   Priority: low

======================================================================
Column: send_hour_velocity
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.253  |  Median: 0.133  |  Std: 0.451
   Range: [-0.367, 1.267]
   Percentiles: 1%=-0.343, 25%=-0.083, 75%=0.550, 99%=1.207

📈 Shape Analysis:
   Skewness: 0.72 (Right-skewed)
   Kurtosis: -0.26 (Light tails)
   Zeros: 1 (5.3%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.72)
   Priority: low

======================================================================
Column: send_hour_velocity_pct
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.689  |  Median: 0.308  |  Std: 1.109
   Range: [-0.550, 3.111]
   Percentiles: 1%=-0.530, 25%=-0.167, 75%=1.530, 99%=3.077

📈 Shape Analysis:
   Skewness: 0.96 (Right-skewed)
   Kurtosis: 0.04 (Light tails)
   Zeros: 1 (5.3%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.96)
   Priority: low

======================================================================
Column: bounced_velocity_pct
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: 0.00)
   Priority: low

======================================================================
Column: time_to_open_hours_velocity
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.051  |  Median: 0.000  |  Std: 0.175
   Range: [-0.170, 0.490]
   Percentiles: 1%=-0.165, 25%=0.000, 75%=0.030, 99%=0.476

📈 Shape Analysis:
   Skewness: 1.45 (Right-skewed)
   Kurtosis: 1.73 (Light tails)
   Zeros: 11 (57.9%)
   Outliers (IQR): 7 (36.8%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (57.9%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: __index_level_0___velocity
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 658.804  |  Median: 40.400  |  Std: 1008.499
   Range: [21.067, 2790.533]
   Percentiles: 1%=21.241, 25%=27.667, 75%=912.133, 99%=2760.965

📈 Shape Analysis:
   Skewness: 1.39 (Right-skewed)
   Kurtosis: 0.38 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 3 (15.8%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.39)
   Priority: medium

======================================================================
Column: __index_level_0___velocity_pct
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.593  |  Median: 0.022  |  Std: 0.944
   Range: [0.008, 3.348]
   Percentiles: 1%=0.008, 25%=0.010, 75%=1.020, 99%=3.194

📈 Shape Analysis:
   Skewness: 1.91 (Right-skewed)
   Kurtosis: 3.46 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 1 (5.3%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.91)
   Priority: medium

======================================================================
Column: opened_acceleration
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.037
   Range: [-0.067, 0.033]
   Percentiles: 1%=-0.063, 25%=0.000, 75%=0.025, 99%=0.033

📈 Shape Analysis:
   Skewness: -1.37 (Left-skewed)
   Kurtosis: 2.50 (Light tails)
   Zeros: 3 (50.0%)
   Outliers (IQR): 1 (16.7%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (50.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_acceleration
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: -0.006  |  Median: 0.000  |  Std: 0.033
   Range: [-0.067, 0.033]
   Percentiles: 1%=-0.063, 25%=0.000, 75%=0.000, 99%=0.032

📈 Shape Analysis:
   Skewness: -1.44 (Left-skewed)
   Kurtosis: 3.60 (Heavy tails/outliers)
   Zeros: 4 (66.7%)
   Outliers (IQR): 2 (33.3%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (66.7%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: send_hour_acceleration
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.778  |  Median: 0.450  |  Std: 1.041
   Range: [-0.100, 2.833]
   Percentiles: 1%=-0.078, 25%=0.358, 75%=0.642, 99%=2.727

📈 Shape Analysis:
   Skewness: 2.09 (Right-skewed)
   Kurtosis: 4.80 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (33.3%)

🔧 Recommended Transformation: yeo_johnson
   Reason: High skewness (2.09) with negative values present
   Priority: high
   ⚠️ Yeo-Johnson handles negative values unlike log/sqrt

======================================================================
Column: send_hour_momentum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 10.582  |  Median: 2.267  |  Std: 17.783
   Range: [-3.300, 64.600]
   Percentiles: 1%=-3.174, 25%=-1.033, 75%=17.017, 99%=59.188

📈 Shape Analysis:
   Skewness: 1.87 (Right-skewed)
   Kurtosis: 3.64 (Heavy tails/outliers)
   Zeros: 1 (5.3%)
   Outliers (IQR): 1 (5.3%)

🔧 Recommended Transformation: yeo_johnson
   Reason: Moderate skewness (1.87) with negative values
   Priority: medium

======================================================================
Column: time_to_open_hours_acceleration
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.061  |  Median: 0.000  |  Std: 0.249
   Range: [-0.267, 0.490]
   Percentiles: 1%=-0.253, 25%=0.000, 75%=0.105, 99%=0.473

📈 Shape Analysis:
   Skewness: 0.86 (Right-skewed)
   Kurtosis: 2.11 (Light tails)
   Zeros: 3 (50.0%)
   Outliers (IQR): 2 (33.3%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (50.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: time_to_open_hours_momentum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.994  |  Median: 0.000  |  Std: 2.421
   Range: [-0.000, 7.913]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.054, 99%=7.785

📈 Shape Analysis:
   Skewness: 2.47 (Right-skewed)
   Kurtosis: 5.03 (Heavy tails/outliers)
   Zeros: 14 (73.7%)
   Outliers (IQR): 4 (21.1%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (73.7%) combined with high skewness (2.47)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: __index_level_0___acceleration
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 832.994  |  Median: 495.983  |  Std: 1065.280
   Range: [0.400, 2664.900]
   Percentiles: 1%=0.663, 25%=8.175, 75%=1245.342, 99%=2598.407

📈 Shape Analysis:
   Skewness: 1.14 (Right-skewed)
   Kurtosis: 0.66 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.14)
   Priority: medium

======================================================================
Column: __index_level_0___momentum
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 83208565.132  |  Median: 2448302.633  |  Std: 157869288.265
   Range: [627926.833, 462265799.333]
   Percentiles: 1%=629557.627, 25%=1819009.567, 75%=42450801.783, 99%=452868287.189

📈 Shape Analysis:
   Skewness: 1.80 (Right-skewed)
   Kurtosis: 1.70 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 4 (21.1%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.80)
   Priority: medium

======================================================================
Column: opened_beginning
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.485  |  Median: 1.000  |  Std: 1.921
   Range: [0.000, 16.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=5.440

📈 Shape Analysis:
   Skewness: 4.67 (Right-skewed)
   Kurtosis: 33.49 (Heavy tails/outliers)
   Zeros: 30 (30.9%)
   Outliers (IQR): 1 (1.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (30.9%) combined with high skewness (4.67)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: opened_end
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.289  |  Median: 1.000  |  Std: 1.607
   Range: [0.000, 10.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=2.000, 99%=7.120

📈 Shape Analysis:
   Skewness: 2.41 (Right-skewed)
   Kurtosis: 9.21 (Heavy tails/outliers)
   Zeros: 38 (39.2%)
   Outliers (IQR): 2 (2.1%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (39.2%) combined with high skewness (2.41)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: opened_trend_ratio
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.862  |  Median: 0.667  |  Std: 0.962
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=3.670

📈 Shape Analysis:
   Skewness: 1.44 (Right-skewed)
   Kurtosis: 1.70 (Light tails)
   Zeros: 21 (31.3%)
   Outliers (IQR): 6 (9.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (31.3%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_beginning
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.485  |  Median: 0.000  |  Std: 0.723
   Range: [0.000, 4.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.000, 99%=2.080

📈 Shape Analysis:
   Skewness: 1.83 (Right-skewed)
   Kurtosis: 4.80 (Heavy tails/outliers)
   Zeros: 60 (61.9%)
   Outliers (IQR): 1 (1.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (61.9%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: clicked_end
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.309  |  Median: 0.000  |  Std: 0.727
   Range: [0.000, 5.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=3.080

📈 Shape Analysis:
   Skewness: 3.77 (Right-skewed)
   Kurtosis: 19.06 (Heavy tails/outliers)
   Zeros: 75 (77.3%)
   Outliers (IQR): 22 (22.7%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (77.3%) combined with high skewness (3.77)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: clicked_trend_ratio
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.304  |  Median: 0.000  |  Std: 0.598
   Range: [0.000, 2.500]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.500, 99%=2.320

📈 Shape Analysis:
   Skewness: 2.26 (Right-skewed)
   Kurtosis: 5.17 (Heavy tails/outliers)
   Zeros: 27 (73.0%)
   Outliers (IQR): 2 (5.4%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (73.0%) combined with high skewness (2.26)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: send_hour_beginning
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 82.887  |  Median: 70.000  |  Std: 55.988
   Range: [9.000, 429.000]
   Percentiles: 1%=10.920, 25%=51.000, 75%=105.000, 99%=236.040

📈 Shape Analysis:
   Skewness: 2.87 (Right-skewed)
   Kurtosis: 14.67 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 3 (3.1%)

🔧 Recommended Transformation: log_transform
   Reason: High positive skewness (2.87) with all positive values
   Priority: high

======================================================================
Column: send_hour_end
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 85.948  |  Median: 82.000  |  Std: 59.929
   Range: [10.000, 472.000]
   Percentiles: 1%=10.960, 25%=53.000, 75%=103.000, 99%=299.200

📈 Shape Analysis:
   Skewness: 3.19 (Right-skewed)
   Kurtosis: 18.09 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (2.1%)

🔧 Recommended Transformation: log_transform
   Reason: High positive skewness (3.19) with all positive values
   Priority: high

======================================================================
Column: send_hour_trend_ratio
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.197  |  Median: 1.057  |  Std: 0.692
   Range: [0.120, 3.850]
   Percentiles: 1%=0.208, 25%=0.685, 75%=1.579, 99%=3.141

📈 Shape Analysis:
   Skewness: 1.18 (Right-skewed)
   Kurtosis: 1.69 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (2.1%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.18)
   Priority: medium

======================================================================
Column: time_to_open_hours_beginning
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 5.643  |  Median: 2.300  |  Std: 10.880
   Range: [0.000, 95.300]
   Percentiles: 1%=0.000, 25%=0.000, 75%=7.800, 99%=25.700

📈 Shape Analysis:
   Skewness: 6.08 (Right-skewed)
   Kurtosis: 48.31 (Heavy tails/outliers)
   Zeros: 31 (32.0%)
   Outliers (IQR): 4 (4.1%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (32.0%) combined with high skewness (6.08)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: time_to_open_hours_end
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 4.601  |  Median: 1.800  |  Std: 7.215
   Range: [0.000, 39.200]
   Percentiles: 1%=0.000, 25%=0.000, 75%=6.400, 99%=36.896

📈 Shape Analysis:
   Skewness: 2.66 (Right-skewed)
   Kurtosis: 8.69 (Heavy tails/outliers)
   Zeros: 38 (39.2%)
   Outliers (IQR): 6 (6.2%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (39.2%) combined with high skewness (2.66)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: time_to_open_hours_trend_ratio
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 3.227  |  Median: 0.431  |  Std: 8.110
   Range: [0.000, 40.500]
   Percentiles: 1%=0.000, 25%=0.000, 75%=1.867, 99%=38.062

📈 Shape Analysis:
   Skewness: 3.55 (Right-skewed)
   Kurtosis: 12.30 (Heavy tails/outliers)
   Zeros: 20 (30.3%)
   Outliers (IQR): 8 (12.1%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (30.3%) combined with high skewness (3.55)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: __index_level_0___beginning
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 97256.062  |  Median: 83731.000  |  Std: 88709.393
   Range: [1408.000, 725773.000]
   Percentiles: 1%=1632.640, 25%=46139.000, 75%=122678.000, 99%=323893.000

📈 Shape Analysis:
   Skewness: 3.94 (Right-skewed)
   Kurtosis: 25.64 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 3 (3.1%)

🔧 Recommended Transformation: log_transform
   Reason: High positive skewness (3.94) with all positive values
   Priority: high

======================================================================
Column: __index_level_0___end
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 399846.381  |  Median: 419682.000  |  Std: 339701.239
   Range: [8797.000, 2639952.000]
   Percentiles: 1%=11373.640, 25%=163099.000, 75%=520778.000, 99%=1494765.120

📈 Shape Analysis:
   Skewness: 3.25 (Right-skewed)
   Kurtosis: 19.38 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 2 (2.1%)

🔧 Recommended Transformation: log_transform
   Reason: High positive skewness (3.25) with all positive values
   Priority: high

======================================================================
Column: __index_level_0___trend_ratio
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 5.081  |  Median: 4.250  |  Std: 3.499
   Range: [0.295, 20.306]
   Percentiles: 1%=0.493, 25%=2.730, 75%=6.248, 99%=18.390

📈 Shape Analysis:
   Skewness: 1.86 (Right-skewed)
   Kurtosis: 4.86 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 4 (4.1%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.86)
   Priority: medium

======================================================================
Column: days_since_last_event_y
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 100 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: days_since_first_event_y
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 2223.570  |  Median: 2743.500  |  Std: 1049.794
   Range: [0.000, 3278.000]
   Percentiles: 1%=34.650, 25%=1280.750, 75%=3052.750, 99%=3264.140

📈 Shape Analysis:
   Skewness: -0.85 (Left-skewed)
   Kurtosis: -0.77 (Light tails)
   Zeros: 1 (1.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.85)
   Priority: low

======================================================================
Column: active_span_days
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 2223.570  |  Median: 2743.500  |  Std: 1049.794
   Range: [0.000, 3278.000]
   Percentiles: 1%=34.650, 25%=1280.750, 75%=3052.750, 99%=3264.140

📈 Shape Analysis:
   Skewness: -0.85 (Left-skewed)
   Kurtosis: -0.77 (Light tails)
   Zeros: 1 (1.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.85)
   Priority: low

======================================================================
Column: recency_ratio
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.000  |  Std: 0.000
   Range: [0.000, 0.000]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=0.000

📈 Shape Analysis:
   Skewness: 0.00 (Symmetric)
   Kurtosis: 0.00 (Light tails)
   Zeros: 100 (100.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Significant zero-inflation (100.0%)
   Priority: medium
   ⚠️ Many zero values may indicate a mixture distribution

======================================================================
Column: event_frequency
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.335  |  Median: 0.199  |  Std: 0.455
   Range: [0.116, 3.584]
   Percentiles: 1%=0.135, 25%=0.174, 75%=0.269, 99%=1.881

📈 Shape Analysis:
   Skewness: 4.87 (Right-skewed)
   Kurtosis: 28.38 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 13 (13.1%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (4.87) with significant outliers (13.1%)
   Priority: high

======================================================================
Column: inter_event_gap_mean
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 151.759  |  Median: 161.647  |  Std: 56.283
   Range: [8.692, 322.500]
   Percentiles: 1%=17.547, 25%=131.375, 75%=186.657, 99%=277.175

📈 Shape Analysis:
   Skewness: -0.52 (Left-skewed)
   Kurtosis: 0.82 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 10 (10.1%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (10.1%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: inter_event_gap_std
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 131.408  |  Median: 139.254  |  Std: 58.384
   Range: [0.000, 269.852]
   Percentiles: 1%=0.000, 25%=94.008, 75%=170.607, 99%=263.212

📈 Shape Analysis:
   Skewness: -0.29 (Symmetric)
   Kurtosis: -0.23 (Light tails)
   Zeros: 2 (2.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.29)
   Priority: low

======================================================================
Column: inter_event_gap_max
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 458.980  |  Median: 481.000  |  Std: 206.187
   Range: [35.000, 975.000]
   Percentiles: 1%=35.000, 25%=316.000, 75%=608.500, 99%=853.480

📈 Shape Analysis:
   Skewness: -0.09 (Symmetric)
   Kurtosis: -0.44 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 0 (0.0%)

🔧 Recommended Transformation: none
   Reason: Distribution is approximately normal (skewness: -0.09)
   Priority: low

======================================================================
Column: regularity_score
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.166  |  Median: 0.107  |  Std: 0.211
   Range: [0.000, 1.000]
   Percentiles: 1%=0.000, 25%=0.005, 75%=0.221, 99%=1.000

📈 Shape Analysis:
   Skewness: 2.10 (Right-skewed)
   Kurtosis: 4.91 (Heavy tails/outliers)
   Zeros: 25 (25.3%)
   Outliers (IQR): 8 (8.1%)

🔧 Recommended Transformation: cap_then_log
   Reason: High skewness (2.10) with significant outliers (8.1%)
   Priority: high

======================================================================
Column: send_hour_vs_cohort_mean
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: -0.000  |  Median: -2.620  |  Std: 8.053
   Range: [-11.620, 33.380]
   Percentiles: 1%=-10.630, 25%=-4.870, 75%=2.380, 99%=20.510

📈 Shape Analysis:
   Skewness: 1.47 (Right-skewed)
   Kurtosis: 2.50 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 8 (8.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: Moderate skewness (1.47) with negative values
   Priority: medium

======================================================================
Column: send_hour_vs_cohort_pct
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.000  |  Median: 0.851  |  Std: 0.457
   Range: [0.341, 2.894]
   Percentiles: 1%=0.397, 25%=0.724, 75%=1.135, 99%=2.164

📈 Shape Analysis:
   Skewness: 1.47 (Right-skewed)
   Kurtosis: 2.50 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 8 (8.0%)

🔧 Recommended Transformation: sqrt_transform
   Reason: Moderate skewness (1.47)
   Priority: medium

======================================================================
Column: send_hour_cohort_zscore
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: -0.000  |  Median: -0.325  |  Std: 1.000
   Range: [-1.443, 4.145]
   Percentiles: 1%=-1.320, 25%=-0.605, 75%=0.296, 99%=2.547

📈 Shape Analysis:
   Skewness: 1.47 (Right-skewed)
   Kurtosis: 2.50 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 8 (8.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: Moderate skewness (1.47) with negative values
   Priority: medium

======================================================================
Column: time_to_open_hours_vs_cohort_mean
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: -0.736  |  Std: 2.765
   Range: [-0.736, 18.564]
   Percentiles: 1%=-0.736, 25%=-0.736, 75%=-0.736, 99%=14.010

📈 Shape Analysis:
   Skewness: 5.04 (Right-skewed)
   Kurtosis: 27.56 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 14 (14.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: High skewness (5.04) with negative values present
   Priority: high
   ⚠️ Yeo-Johnson handles negative values unlike log/sqrt

======================================================================
Column: time_to_open_hours_vs_cohort_pct
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.000  |  Median: 0.000  |  Std: 3.757
   Range: [0.000, 26.223]
   Percentiles: 1%=0.000, 25%=0.000, 75%=0.000, 99%=20.035

📈 Shape Analysis:
   Skewness: 5.04 (Right-skewed)
   Kurtosis: 27.56 (Heavy tails/outliers)
   Zeros: 86 (86.0%)
   Outliers (IQR): 14 (14.0%)

🔧 Recommended Transformation: zero_inflation_handling
   Reason: Zero-inflation (86.0%) combined with high skewness (5.04)
   Priority: high
   ⚠️ Consider creating a binary indicator for zeros plus log transform of non-zero values

======================================================================
Column: time_to_open_hours_cohort_zscore
Type: numeric_discrete (Confidence: 70%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: -0.266  |  Std: 1.000
   Range: [-0.266, 6.713]
   Percentiles: 1%=-0.266, 25%=-0.266, 75%=-0.266, 99%=5.066

📈 Shape Analysis:
   Skewness: 5.04 (Right-skewed)
   Kurtosis: 27.56 (Heavy tails/outliers)
   Zeros: 0 (0.0%)
   Outliers (IQR): 14 (14.0%)

🔧 Recommended Transformation: yeo_johnson
   Reason: High skewness (5.04) with negative values present
   Priority: high
   ⚠️ Yeo-Johnson handles negative values unlike log/sqrt

======================================================================
Column: __index_level_0___vs_cohort_mean
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 3139.960  |  Std: 39891.718
   Range: [-67513.540, 89344.460]
   Percentiles: 1%=-67233.370, 25%=-30224.540, 75%=6503.960, 99%=88891.040

📈 Shape Analysis:
   Skewness: 0.67 (Right-skewed)
   Kurtosis: 0.19 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 13 (13.0%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (13.0%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: __index_level_0___vs_cohort_pct
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 1.000  |  Median: 1.041  |  Std: 0.523
   Range: [0.115, 2.171]
   Percentiles: 1%=0.119, 25%=0.604, 75%=1.085, 99%=2.165

📈 Shape Analysis:
   Skewness: 0.67 (Right-skewed)
   Kurtosis: 0.19 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 13 (13.0%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (13.0%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

======================================================================
Column: __index_level_0___cohort_zscore
Type: numeric_continuous (Confidence: 90%)
----------------------------------------------------------------------
📊 Distribution Statistics:
   Mean: 0.000  |  Median: 0.079  |  Std: 1.000
   Range: [-1.692, 2.240]
   Percentiles: 1%=-1.685, 25%=-0.758, 75%=0.163, 99%=2.228

📈 Shape Analysis:
   Skewness: 0.67 (Right-skewed)
   Kurtosis: 0.19 (Light tails)
   Zeros: 0 (0.0%)
   Outliers (IQR): 13 (13.0%)

🔧 Recommended Transformation: cap_outliers
   Reason: Significant outliers (13.0%) despite low skewness
   Priority: medium
   ⚠️ Consider investigating outlier causes before capping

In [6]:
if numeric_cols:
    stats_data = []
    for col_name in numeric_cols:
        series = df[col_name].dropna()
        if len(series) > 0:
            series_np = series.to_numpy()
            stats_data.append({
                "feature": col_name,
                "count": len(series),
                "mean": series.mean(),
                "std": series.std(),
                "min": series.min(),
                "25%": series.quantile(0.25),
                "50%": series.quantile(0.50),
                "75%": series.quantile(0.75),
                "95%": series.quantile(0.95),
                "99%": series.quantile(0.99),
                "max": series.max(),
                "skewness": stats.skew(series_np),
                "kurtosis": stats.kurtosis(series_np)
            })

    stats_df = native_pd.DataFrame(stats_data)

    display_stats = stats_df.copy()
    for col in ["mean", "std", "min", "25%", "50%", "75%", "95%", "99%", "max"]:
        display_stats[col] = display_stats[col].apply(lambda x: f"{x:.3f}")
    display_stats["skewness"] = display_stats["skewness"].apply(lambda x: f"{x:.3f}")
    display_stats["kurtosis"] = display_stats["kurtosis"].apply(lambda x: f"{x:.3f}")

    print("=" * 80)
    print("NUMERICAL FEATURE STATISTICS")
    print("=" * 80)
    display_table(display_stats)

================================================================================
NUMERICAL FEATURE STATISTICS
================================================================================

## 4.5 Distribution Summary & Transformation Plan

This table summarizes all numeric columns with their recommended transformations.

In [7]:
# Build transformation summary table
summary_data = []
for col_name in numeric_cols:
    analysis = analyses.get(col_name)
    rec = recommendations.get(col_name)

    if analysis and rec:
        summary_data.append({
            "Column": col_name,
            "Skewness": f"{analysis.skewness:.2f}",
            "Kurtosis": f"{analysis.kurtosis:.2f}",
            "Zeros %": f"{analysis.zero_percentage:.1f}%",
            "Outliers %": f"{analysis.outlier_percentage:.1f}%",
            "Transform": rec.recommended_transform.value,
            "Priority": rec.priority
        })

        # Add Gold transformation recommendation if not "none"
        if rec.recommended_transform != TransformationType.NONE and registry.gold:
            registry.add_gold_transformation(
                column=col_name,
                transform=rec.recommended_transform.value,
                parameters=rec.parameters,
                rationale=rec.reason,
                source_notebook="04_column_deep_dive"
            )

if summary_data:
    summary_df = native_pd.DataFrame(summary_data)
    display_table(summary_df)

    # Show how many transformation recommendations were added
    transform_count = sum(1 for r in recommendations.values() if r and r.recommended_transform != TransformationType.NONE)
    if transform_count > 0 and registry.gold:
        print(f"\n✅ Added {transform_count} transformation recommendations to Gold layer")
else:
    console.info("No numeric columns to summarize")

✅ Added 140 transformation recommendations to Gold layer

## 4.6 Categorical Columns Analysis

**📖 Distribution Metrics (Analogues to Numeric Skewness/Kurtosis):**

| Metric | Interpretation | Action |
|--------|---------------|--------|
| **Imbalance Ratio** | Largest / Smallest category count | > 10: Consider grouping rare categories |
| **Entropy** | Diversity measure (0 = one category, higher = more uniform) | Low entropy: May need stratified sampling |
| **Top-3 Concentration** | % of data in top 3 categories | > 90%: Rare categories may cause issues |
| **Rare Category %** | Categories with < 1% of data | High %: Group into "Other" category |

**📖 Encoding Recommendations:**
- **Low cardinality (≤5)** → One-hot encoding
- **Medium cardinality (6-20)** → One-hot or Target encoding
- **High cardinality (>20)** → Target encoding or Frequency encoding
- **Cyclical (days, months)** → Sin/Cos encoding

**⚠️ Common Issues:**
- Rare categories can cause overfitting with one-hot encoding
- High cardinality + one-hot = feature explosion
- Imbalanced categories may need special handling in train/test splits

In [8]:
# Use framework's CategoricalDistributionAnalyzer
cat_analyzer = CategoricalDistributionAnalyzer()

categorical_cols = [
    name for name, col in findings.columns.items()
    if col.inferred_type in [ColumnType.CATEGORICAL_NOMINAL, ColumnType.CATEGORICAL_ORDINAL, ColumnType.CATEGORICAL_CYCLICAL]
    and col.inferred_type != ColumnType.TEXT  # TEXT columns processed separately in 02a
    and name not in TEMPORAL_METADATA_COLS
]

# Analyze all categorical columns
cat_analyses = cat_analyzer.analyze_dataframe(df, categorical_cols)

# Get encoding recommendations
cyclical_cols = [name for name, col in findings.columns.items()
                 if col.inferred_type == ColumnType.CATEGORICAL_CYCLICAL]
cat_recommendations = cat_analyzer.get_all_recommendations(df, categorical_cols, cyclical_columns=cyclical_cols)

for col_name in categorical_cols:
    col_info = findings.columns[col_name]
    analysis = cat_analyses.get(col_name)
    rec = next((r for r in cat_recommendations if r.column_name == col_name), None)

    print(f"\n{'='*70}")
    print(f"Column: {col_name}")
    print(f"Type: {col_info.inferred_type.value} (Confidence: {col_info.confidence:.0%})")
    print("-" * 70)

    if analysis:
        print("\n📊 Distribution Metrics:")
        print(f"   Categories: {analysis.category_count}")
        print(f"   Imbalance Ratio: {analysis.imbalance_ratio:.1f}x (largest/smallest)")
        print(f"   Entropy: {analysis.entropy:.2f} ({analysis.normalized_entropy*100:.0f}% of max)")
        print(f"   Top-1 Concentration: {analysis.top1_concentration:.1f}%")
        print(f"   Top-3 Concentration: {analysis.top3_concentration:.1f}%")
        print(f"   Rare Categories (<1%): {analysis.rare_category_count}")

        # Interpretation
        print("\n📈 Interpretation:")
        if analysis.has_low_diversity:
            print("   ⚠️ LOW DIVERSITY: Distribution dominated by few categories")
        elif analysis.normalized_entropy > 0.9:
            print("   ✓ HIGH DIVERSITY: Categories are relatively balanced")
        else:
            print("   ✓ MODERATE DIVERSITY: Some category dominance but acceptable")

        if analysis.imbalance_ratio > 100:
            print("   🔴 SEVERE IMBALANCE: Rarest category has very few samples")
        elif analysis.is_imbalanced:
            print("   🟡 MODERATE IMBALANCE: Consider grouping rare categories")

        # Recommendations
        if rec:
            print("\n🔧 Recommendations:")
            print(f"   Encoding: {rec.encoding_type.value}")
            print(f"   Reason: {rec.reason}")
            print(f"   Priority: {rec.priority}")

            if rec.preprocessing_steps:
                print("   Preprocessing:")
                for step in rec.preprocessing_steps:
                    print(f"      • {step}")

            if rec.warnings:
                for warn in rec.warnings:
                    print(f"   ⚠️ {warn}")

    # Visualization
    value_counts = df[col_name].value_counts()
    subtitle = f"Entropy: {analysis.normalized_entropy*100:.0f}% | Imbalance: {analysis.imbalance_ratio:.1f}x | Rare: {analysis.rare_category_count}" if analysis else ""
    fig = charts.bar_chart(
        value_counts.head(10).index.tolist(),
        value_counts.head(10).values.tolist(),
        title=f"Top Categories: {col_name}<br><sub>{subtitle}</sub>"
    )
    display_figure(fig)

# Summary table and add recommendations to registry
if cat_analyses:
    print("\n" + "=" * 70)
    print("CATEGORICAL COLUMNS SUMMARY")
    print("=" * 70)
    summary_data = []
    for col_name, analysis in cat_analyses.items():
        rec = next((r for r in cat_recommendations if r.column_name == col_name), None)
        summary_data.append({
            "Column": col_name,
            "Categories": analysis.category_count,
            "Imbalance": f"{analysis.imbalance_ratio:.1f}x",
            "Entropy": f"{analysis.normalized_entropy*100:.0f}%",
            "Top-3 Conc.": f"{analysis.top3_concentration:.1f}%",
            "Rare (<1%)": analysis.rare_category_count,
            "Encoding": rec.encoding_type.value if rec else "N/A"
        })

        # Add encoding recommendation to Gold layer
        if rec and registry.gold:
            registry.add_gold_encoding(
                column=col_name,
                method=rec.encoding_type.value,
                rationale=rec.reason,
                source_notebook="04_column_deep_dive"
            )

    display_table(native_pd.DataFrame(summary_data))

    if registry.gold:
        print(f"\n✅ Added {len(cat_recommendations)} encoding recommendations to Gold layer")

======================================================================
Column: lifecycle_quadrant
Type: categorical_nominal (Confidence: 90%)
----------------------------------------------------------------------

📊 Distribution Metrics:
   Categories: 4
   Imbalance Ratio: 2.1x (largest/smallest)
   Entropy: 1.90 (95% of max)
   Top-1 Concentration: 34.0%
   Top-3 Concentration: 84.0%
   Rare Categories (<1%): 0

📈 Interpretation:
   ✓ HIGH DIVERSITY: Categories are relatively balanced

🔧 Recommendations:
   Encoding: one_hot
   Reason: Low cardinality (4 categories) - safe feature expansion
   Priority: low

======================================================================
Column: recency_bucket
Type: categorical_nominal (Confidence: 90%)
----------------------------------------------------------------------

📊 Distribution Metrics:
   Categories: 5
   Imbalance Ratio: 21.7x (largest/smallest)
   Entropy: 1.56 (67% of max)
   Top-1 Concentration: 65.0%
   Top-3 Concentration: 91.0%
   Rare Categories (<1%): 0

📈 Interpretation:
   ✓ MODERATE DIVERSITY: Some category dominance but acceptable
   🟡 MODERATE IMBALANCE: Consider grouping rare categories

🔧 Recommendations:
   Encoding: one_hot
   Reason: Low cardinality (5 categories) - safe feature expansion
   Priority: low
   ⚠️ Use stratified sampling to preserve rare category representation

======================================================================
CATEGORICAL COLUMNS SUMMARY
======================================================================

✅ Added 2 encoding recommendations to Gold layer

## 4.7 Datetime Columns Analysis

**📖 Unlike numeric transformations, datetime analysis recommends NEW FEATURES to create:**

| Recommendation Type | Purpose | Examples |
|---------------------|---------|----------|
| **Feature Engineering** | Create predictive features from dates | `days_since_signup`, `tenure_years`, `month_sin_cos` |
| **Modeling Strategy** | How to structure train/test | Time-based splits when trends detected |
| **Data Quality** | Issues to address before modeling | Placeholder dates (1/1/1900) to filter |

**📖 Feature Engineering Strategies:**
- **Recency**: `days_since_X` - How recent was the event? (useful for predicting behavior)
- **Tenure**: `tenure_years` - How long has customer been active? (maturity/loyalty)
- **Duration**: `days_between_A_and_B` - Time between events (e.g., signup to first purchase)
- **Cyclical**: `month_sin`, `month_cos` - Preserves that December is near January
- **Categorical**: `is_weekend`, `is_quarter_end` - Behavioral indicators

In [9]:
from customer_retention.stages.profiling.temporal_analyzer import TemporalRecommendationType

datetime_cols = [
    name for name, col in findings.columns.items()
    if col.inferred_type == ColumnType.DATETIME
    and name not in TEMPORAL_METADATA_COLS
]

temporal_analyzer = TemporalAnalyzer()

# Store all datetime recommendations grouped by type
feature_engineering_recs = []
modeling_strategy_recs = []
data_quality_recs = []
datetime_summaries = []

for col_name in datetime_cols:
    col_info = findings.columns[col_name]
    print(f"\n{'='*70}")
    print(f"Column: {col_name}")
    print(f"Type: {col_info.inferred_type.value} (Confidence: {col_info.confidence:.0%})")
    print(f"{'='*70}")

    date_series = to_datetime(df[col_name], errors='coerce', format='mixed')
    valid_dates = date_series.dropna()

    print(f"\n📅 Date Range: {valid_dates.min()} to {valid_dates.max()}")
    print(f"   Nulls: {date_series.isna().sum():,} ({date_series.isna().mean()*100:.1f}%)")

    # Basic temporal analysis
    analysis = temporal_analyzer.analyze(date_series)
    print(f"   Auto-detected granularity: {analysis.granularity.value}")
    print(f"   Span: {analysis.span_days:,} days ({analysis.span_days/365:.1f} years)")

    # Growth analysis
    growth = temporal_analyzer.calculate_growth_rate(date_series)
    if growth.get("has_data"):
        print("\n📈 Growth Analysis:")
        print(f"   Trend: {growth['trend_direction'].upper()}")
        print(f"   Overall growth: {growth['overall_growth_pct']:+.1f}%")
        print(f"   Avg monthly growth: {growth['avg_monthly_growth']:+.1f}%")

    # Seasonality analysis
    seasonality = temporal_analyzer.analyze_seasonality(date_series)
    if seasonality.has_seasonality:
        print("\n🔄 Seasonality Detected:")
        print(f"   Peak months: {', '.join(seasonality.peak_periods[:3])}")
        print(f"   Trough months: {', '.join(seasonality.trough_periods[:3])}")
        print(f"   Seasonal strength: {seasonality.seasonal_strength:.2f}")

    # Get recommendations using framework
    other_dates = [c for c in datetime_cols if c != col_name]
    recommendations = temporal_analyzer.recommend_features(date_series, col_name, other_date_columns=other_dates)

    # Group by recommendation type
    col_feature_recs = [r for r in recommendations if r.recommendation_type == TemporalRecommendationType.FEATURE_ENGINEERING]
    col_modeling_recs = [r for r in recommendations if r.recommendation_type == TemporalRecommendationType.MODELING_STRATEGY]
    col_quality_recs = [r for r in recommendations if r.recommendation_type == TemporalRecommendationType.DATA_QUALITY]

    feature_engineering_recs.extend(col_feature_recs)
    modeling_strategy_recs.extend(col_modeling_recs)
    data_quality_recs.extend(col_quality_recs)

    # Display recommendations grouped by type
    if col_feature_recs:
        print("\n🛠️ FEATURES TO CREATE:")
        for rec in col_feature_recs:
            priority_icon = "🔴" if rec.priority == "high" else "🟡" if rec.priority == "medium" else "✓"
            print(f"   {priority_icon} {rec.feature_name} ({rec.category})")
            print(f"      Why: {rec.reason}")
            if rec.code_hint:
                print(f"      Code: {rec.code_hint}")

    if col_modeling_recs:
        print("\n⚙️ MODELING CONSIDERATIONS:")
        for rec in col_modeling_recs:
            priority_icon = "🔴" if rec.priority == "high" else "🟡" if rec.priority == "medium" else "✓"
            print(f"   {priority_icon} {rec.feature_name}")
            print(f"      Why: {rec.reason}")

    if col_quality_recs:
        print("\n⚠️ DATA QUALITY ISSUES:")
        for rec in col_quality_recs:
            priority_icon = "🔴" if rec.priority == "high" else "🟡" if rec.priority == "medium" else "✓"
            print(f"   {priority_icon} {rec.feature_name}")
            print(f"      Why: {rec.reason}")
            if rec.code_hint:
                print(f"      Code: {rec.code_hint}")

    # Standard extractions always available
    print("\n   Standard extractions available: year, month, day, day_of_week, quarter")

    # Store summary
    datetime_summaries.append({
        "Column": col_name,
        "Span (days)": analysis.span_days,
        "Seasonality": "Yes" if seasonality.has_seasonality else "No",
        "Trend": growth.get('trend_direction', 'N/A').capitalize() if growth.get("has_data") else "N/A",
        "Features to Create": len(col_feature_recs),
        "Modeling Notes": len(col_modeling_recs),
        "Quality Issues": len(col_quality_recs)
    })

    # === VISUALIZATIONS ===

    if growth.get("has_data"):
        fig = charts.growth_summary_indicators(growth, title=f"Growth Summary: {col_name}")
        display_figure(fig)

    chart_type = "line" if analysis.granularity in [TemporalGranularity.DAY, TemporalGranularity.WEEK] else "bar"
    fig = charts.temporal_distribution(analysis, title=f"Records Over Time: {col_name}", chart_type=chart_type)
    display_figure(fig)

    fig = charts.temporal_trend(analysis, title=f"Trend Analysis: {col_name}")
    display_figure(fig)

    yoy_data = temporal_analyzer.year_over_year_comparison(date_series)
    if len(yoy_data) > 1:
        fig = charts.year_over_year_lines(yoy_data, title=f"Year-over-Year: {col_name}")
        display_figure(fig)
        fig = charts.year_month_heatmap(yoy_data, title=f"Records Heatmap: {col_name}")
        display_figure(fig)

    if growth.get("has_data"):
        fig = charts.cumulative_growth_chart(growth["cumulative"], title=f"Cumulative Records: {col_name}")
        display_figure(fig)

    fig = charts.temporal_heatmap(date_series, title=f"Day of Week Distribution: {col_name}")
    display_figure(fig)

# === DATETIME SUMMARY ===
if datetime_summaries:
    print("\n" + "=" * 70)
    print("DATETIME COLUMNS SUMMARY")
    print("=" * 70)
    display_table(native_pd.DataFrame(datetime_summaries))

    # Summary by recommendation type
    print("\n📋 ALL RECOMMENDATIONS BY TYPE:")

    if feature_engineering_recs:
        print(f"\n🛠️ FEATURES TO CREATE ({len(feature_engineering_recs)}):")
        for i, rec in enumerate(feature_engineering_recs, 1):
            priority_icon = "🔴" if rec.priority == "high" else "🟡" if rec.priority == "medium" else "✓"
            print(f"   {i}. {priority_icon} {rec.feature_name}")

    if modeling_strategy_recs:
        print(f"\n⚙️ MODELING CONSIDERATIONS ({len(modeling_strategy_recs)}):")
        for i, rec in enumerate(modeling_strategy_recs, 1):
            priority_icon = "🔴" if rec.priority == "high" else "🟡" if rec.priority == "medium" else "✓"
            print(f"   {i}. {priority_icon} {rec.feature_name}: {rec.reason}")

    if data_quality_recs:
        print(f"\n⚠️ DATA QUALITY TO ADDRESS ({len(data_quality_recs)}):")
        for i, rec in enumerate(data_quality_recs, 1):
            priority_icon = "🔴" if rec.priority == "high" else "🟡" if rec.priority == "medium" else "✓"
            print(f"   {i}. {priority_icon} {rec.feature_name}: {rec.reason}")

    # Add recommendations to registry
    added_derived = 0
    added_modeling = 0

    # Add feature engineering recommendations to Silver layer (derived columns)
    if registry.silver:
        for rec in feature_engineering_recs:
            registry.add_silver_derived(
                column=rec.feature_name,
                expression=rec.code_hint or "",
                feature_type=rec.category,
                rationale=rec.reason,
                source_notebook="04_column_deep_dive"
            )
            added_derived += 1

    # Add modeling strategy recommendations to Bronze layer
    seen_strategies = set()
    for rec in modeling_strategy_recs:
        if rec.feature_name not in seen_strategies:
            registry.add_bronze_modeling_strategy(
                strategy=rec.feature_name,
                column=datetime_cols[0] if datetime_cols else "",
                parameters={"category": rec.category},
                rationale=rec.reason,
                source_notebook="04_column_deep_dive"
            )
            seen_strategies.add(rec.feature_name)
            added_modeling += 1

    print(f"\n✅ Added {added_derived} derived column recommendations to Silver layer")
    print(f"✅ Added {added_modeling} modeling strategy recommendations to Bronze layer")

## 4.8 Type Override (Optional)

If any column types were incorrectly inferred, you can override them here.

**Common overrides:**
- Binary columns detected as numeric → `ColumnType.BINARY`
- IDs detected as numeric → `ColumnType.IDENTIFIER`
- Ordinal categories detected as nominal → `ColumnType.CATEGORICAL_ORDINAL`

In [10]:
# === TYPE OVERRIDES ===
# Uncomment and modify to override any incorrectly inferred types
TYPE_OVERRIDES = {
    # "column_name": ColumnType.NEW_TYPE,
    # Examples:
    # "is_active": ColumnType.BINARY,
    # "user_id": ColumnType.IDENTIFIER,
    # "satisfaction_level": ColumnType.CATEGORICAL_ORDINAL,
}

if TYPE_OVERRIDES:
    print("Applying type overrides:")
    for col_name, new_type in TYPE_OVERRIDES.items():
        if col_name in findings.columns:
            old_type = findings.columns[col_name].inferred_type.value
            findings.columns[col_name].inferred_type = new_type
            findings.columns[col_name].confidence = 1.0
            findings.columns[col_name].evidence.append("Manually overridden")
            print(f"  {col_name}: {old_type} → {new_type.value}")
else:
    print("No type overrides configured.")
    print("To override a type, add entries to TYPE_OVERRIDES dictionary above.")

No type overrides configured.
To override a type, add entries to TYPE_OVERRIDES dictionary above.

## 4.9 Data Segmentation Analysis

**Purpose:** Determine if the dataset contains natural subgroups that might benefit from separate models.

**📖 Why This Matters:**
- Some datasets have distinct customer segments with very different behaviors
- A single model might struggle to capture patterns that vary significantly across segments
- Segmented models can improve accuracy but add maintenance complexity

**Recommendations:**
- **single_model** - Data is homogeneous; one model for all records
- **consider_segmentation** - Some variation exists; evaluate if complexity is worth it
- **strong_segmentation** - Distinct segments with different target rates; separate models likely beneficial

**Important:** This is exploratory guidance only. The final decision depends on business context, model complexity tolerance, and available resources.

In [11]:
from customer_retention.core.compat import is_databricks
from customer_retention.stages.profiling import SegmentAnalyzer, SparkSegmentAnalyzer

MAX_SEGMENT_SAMPLE_SIZE = 50_000

if is_databricks():
    segment_analyzer = SparkSegmentAnalyzer(max_sample_size=MAX_SEGMENT_SAMPLE_SIZE)
else:
    segment_analyzer = SegmentAnalyzer()

# Find target column if detected
target_col = None
for col_name, col_info in findings.columns.items():
    if col_info.inferred_type == ColumnType.TARGET:
        target_col = col_name
        break

# Run segmentation analysis using numeric features
print("="*70)
print("DATA SEGMENTATION ANALYSIS")
print("="*70)

segmentation = segment_analyzer.analyze(
    df,
    target_col=target_col,
    feature_cols=numeric_cols if numeric_cols else None,
    max_segments=5
)

print("\n🎯 Analysis Results:")
print(f"   Method: {segmentation.method.value}")
print(f"   Detected Segments: {segmentation.n_segments}")
print(f"   Cluster Quality Score: {segmentation.quality_score:.2f}")
if segmentation.target_variance_ratio is not None:
    print(f"   Target Variance Ratio: {segmentation.target_variance_ratio:.2f}")

print("\n📊 Segment Profiles:")
for profile in segmentation.profiles:
    target_info = f" | Target Rate: {profile.target_rate*100:.1f}%" if profile.target_rate is not None else ""
    print(f"   Segment {profile.segment_id}: {profile.size:,} records ({profile.size_pct:.1f}%){target_info}")

# Display recommendation card
fig = charts.segment_recommendation_card(segmentation)
display_figure(fig)

# Display segment overview
fig = charts.segment_overview(segmentation, title="Segment Overview")
display_figure(fig)

# Display feature comparison if we have features
if segmentation.n_segments > 1 and any(p.defining_features for p in segmentation.profiles):
    fig = charts.segment_feature_comparison(segmentation, title="Feature Comparison Across Segments")
    display_figure(fig)

print("\n📝 Rationale:")
for reason in segmentation.rationale:
    print(f"   • {reason}")

======================================================================
DATA SEGMENTATION ANALYSIS
======================================================================

🎯 Analysis Results:
   Method: kmeans
   Detected Segments: 1
   Cluster Quality Score: 0.00
   Target Variance Ratio: 0.00

📊 Segment Profiles:
   Segment 0: 100 records (100.0%) | Target Rate: 46.0%

📝 Rationale:
   • Insufficient data for meaningful segmentation

## 4.10 Save Updated Findings

In [12]:
# Save updated findings back to the same file
findings.save(FINDINGS_PATH)
print(f"Updated findings saved to: {FINDINGS_PATH}")

# Save recommendations registry
recommendations_path = FINDINGS_PATH.replace("_findings.yaml", "_recommendations.yaml")
registry.save(recommendations_path)
print(f"Recommendations saved to: {recommendations_path}")

# Summary of recommendations
all_recs = registry.all_recommendations
print("\n📋 Recommendations Summary:")
print(f"   Bronze layer: {len(registry.get_by_layer('bronze'))} recommendations")
print(f"   Silver layer: {len(registry.get_by_layer('silver'))} recommendations")
print(f"   Gold layer: {len(registry.get_by_layer('gold'))} recommendations")
print(f"   Total: {len(all_recs)} recommendations")

Updated findings saved to: /Users/Vital/python/CustomerRetention/experiments/runs/email-f00adbd9/datasets/customer_emails/findings/customer_emails_aggregated_findings.yaml
Recommendations saved to: /Users/Vital/python/CustomerRetention/experiments/runs/email-f00adbd9/datasets/customer_emails/findings/customer_emails_aggregated_recommendations.yaml

📋 Recommendations Summary:
   Bronze layer: 3 recommendations
   Silver layer: 0 recommendations
   Gold layer: 142 recommendations
   Total: 145 recommendations

---

## Summary: What We Learned

In this notebook, we performed a deep dive analysis that included:

1. **Value Range Validation** - Validated rates, binary fields, and non-negative constraints
2. **Numeric Distribution Analysis** - Calculated skewness, kurtosis, and percentiles with transformation recommendations
3. **Categorical Distribution Analysis** - Calculated imbalance ratio, entropy, and concentration with encoding recommendations
4. **Datetime Analysis** - Analyzed seasonality, trends, and patterns with feature engineering recommendations
5. **Data Segmentation** - Evaluated if natural subgroups exist that might benefit from separate models

## Key Metrics Reference

**Numeric Columns:**
| Metric | Threshold | Action |
|--------|-----------|--------|
| Skewness | \|skew\| > 1 | Log transform |
| Kurtosis | > 10 | Cap outliers first |
| Zero % | > 40% | Zero-inflation handling |

**Categorical Columns:**
| Metric | Threshold | Action |
|--------|-----------|--------|
| Imbalance Ratio | > 10x | Group rare categories |
| Entropy | < 50% | Stratified sampling |
| Rare Categories | > 0 | Group into "Other" |

**Datetime Columns:**
| Finding | Action |
|---------|--------|
| Seasonality | Add cyclical month encoding |
| Strong trend | Time-based train/test split |
| Multiple dates | Calculate duration features |
| Placeholder dates | Filter or flag |

## Transformation & Encoding Summary

Review the summary tables above for:
- **Numeric**: Which columns need log transforms, capping, or zero-inflation handling
- **Categorical**: Which encoding to use and whether to group rare categories
- **Datetime**: Which temporal features to engineer based on detected patterns

---

## Next Steps

Continue to **02_source_integrity.ipynb** to:
- Analyze duplicate records and value conflicts
- Deep dive into missing value patterns
- Analyze outliers with IQR method
- Check data consistency
- Get cleaning recommendations

Or jump to **05_feature_opportunities.ipynb** if you want to see derived feature recommendations.

> **Save Reminder:** Save this notebook (Ctrl+S / Cmd+S) before running the next one.
> The next notebook will automatically export this notebook's HTML documentation from the saved file.